-- FIXME: need support for animations while building

DefineConstruction("construction-zerg", {
  Files = {
    File = "zerg/units/building morph.png",
    Size = {160, 192}},
  ShadowFiles = {
    File = "zerg/units/building morph shadow.png",
    Size = {160, 192}},
  Constructions = {
   {Percent = 0,
    File = "construction",
    Frame = 0},
   {Percent = 1,
    File = "construction",
    Frame = 1},
{Percent = 2,
File = "construction",
Frame = 7},{Percent = 3,
File = "construction",
Frame = 6},{Percent = 4,
File = "construction",
Frame = 7},{Percent = 5,
File = "construction",
Frame = 8},{Percent = 6,
File = "construction",
Frame = 9},{Percent = 7,
File = "construction",
Frame = 8},{Percent = 8,
File = "construction",
Frame = 7},{Percent = 9,
File = "construction",
Frame = 8},{Percent = 10,
File = "construction",
Frame = 9},{Percent = 11,
File = "construction",
Frame = 8},{Percent = 12,
File = "construction",
Frame = 7},{Percent = 13,
File = "construction",
Frame = 8},{Percent = 14,
File = "construction",
Frame = 9},{Percent = 15,
File = "construction",
Frame = 8},{Percent = 16,
File = "construction",
Frame = 7},{Percent = 17,
File = "construction",
Frame = 8},{Percent = 18,
File = "construction",
Frame = 9},{Percent = 19,
File = "construction",
Frame = 8},{Percent = 20,
File = "construction",
Frame = 7},{Percent = 21,
File = "construction",
Frame = 8},{Percent = 22,
File = "construction",
Frame = 9},{Percent = 23,
File = "construction",
Frame = 8},{Percent = 24,
File = "construction",
Frame = 7},{Percent = 25,
File = "construction",
Frame = 8},{Percent = 26,
File = "construction",
Frame = 9},{Percent = 27,
File = "construction",
Frame = 8},{Percent = 28,
File = "construction",
Frame = 7},{Percent = 29,
File = "construction",
Frame = 8},{Percent = 30,
File = "construction",
Frame = 9},{Percent = 31,
File = "construction",
Frame = 8},{Percent = 32,
File = "construction",
Frame = 7},{Percent = 33,
File = "construction",
Frame = 8},{Percent = 34,
File = "construction",
Frame = 9},{Percent = 35,
File = "construction",
Frame = 8},{Percent = 36,
File = "construction",
Frame = 7},{Percent = 37,
File = "construction",
Frame = 8},{Percent = 38,
File = "construction",
Frame = 9},{Percent = 39,
File = "construction",
Frame = 8},{Percent = 40,
File = "construction",
Frame = 7},{Percent = 41,
File = "construction",
Frame = 8},{Percent = 42,
File = "construction",
Frame = 9},{Percent = 43,
File = "construction",
Frame = 8},{Percent = 44,
File = "construction",
Frame = 7},{Percent = 45,
File = "construction",
Frame = 8},{Percent = 46,
File = "construction",
Frame = 9},{Percent = 47,
File = "construction",
Frame = 8},{Percent = 48,
File = "construction",
Frame = 7},{Percent = 49,
File = "construction",
Frame = 8},{Percent = 50,
File = "construction",
Frame = 9},{Percent = 51,
File = "construction",
Frame = 8},{Percent = 52,
File = "construction",
Frame = 7},{Percent = 53,
File = "construction",
Frame = 8},{Percent = 54,
File = "construction",
Frame = 9},{Percent = 55,
File = "construction",
Frame = 8},{Percent = 56,
File = "construction",
Frame = 7},{Percent = 57,
File = "construction",
Frame = 8},{Percent = 58,
File = "construction",
Frame = 9},{Percent = 59,
File = "construction",
Frame = 8},{Percent = 60,
File = "construction",
Frame = 7},{Percent = 61,
File = "construction",
Frame = 8},{Percent = 62,
File = "construction",
Frame = 9},{Percent = 63,
File = "construction",
Frame = 8},{Percent = 64,
File = "construction",
Frame = 7},{Percent = 65,
File = "construction",
Frame = 8},{Percent = 66,
File = "construction",
Frame = 9},{Percent = 67,
File = "construction",
Frame = 8},{Percent = 68,
File = "construction",
Frame = 7},{Percent = 69,
File = "construction",
Frame = 8},{Percent = 70,
File = "construction",
Frame = 9},{Percent = 71,
File = "construction",
Frame = 8},{Percent = 72,
File = "construction",
Frame = 7},{Percent = 73,
File = "construction",
Frame = 8},{Percent = 74,
File = "construction",
Frame = 9},{Percent = 75,
File = "construction",
Frame = 8},{Percent = 76,
File = "construction",
Frame = 7},{Percent = 77,
File = "construction",
Frame = 8},{Percent = 78,
File = "construction",
Frame = 9},{Percent = 79,
File = "construction",
Frame = 8},{Percent = 80,
File = "construction",
Frame = 7},{Percent = 81,
File = "construction",
Frame = 8},{Percent = 82,
File = "construction",
Frame = 9},{Percent = 83,
File = "construction",
Frame = 8},{Percent = 84,
File = "construction",
Frame = 7},{Percent = 85,
File = "construction",
Frame = 8},{Percent = 86,
File = "construction",
Frame = 9},{Percent = 87,
File = "construction",
Frame = 8},{Percent = 88,
File = "construction",
Frame = 7},{Percent = 89,
File = "construction",
Frame = 8},{Percent = 90,
File = "construction",
Frame = 9},{Percent = 91,
File = "construction",
Frame = 8},{Percent = 92,
File = "construction",
Frame = 7},{Percent = 93,
File = "construction",
Frame = 8},{Percent = 94,
File = "construction",
Frame = 9},{Percent = 95,
File = "construction",
Frame = 8},{Percent = 96,
File = "construction",
Frame = 7},{Percent = 97,
File = "construction",
Frame = 8},{Percent = 98,
File = "construction",
Frame = 9},{Percent = 99,
File = "construction",
Frame = 8},{Percent = 100,
File = "construction",
Frame = 7},
}
})
