#!/bin/sh

set -e

# Source debconf library
. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

if [ "$1" != "configure" ] && [ "$1" != "reconfigure" ]; then
	exit 0;
fi

if [ "$1" = "configure" ] && [ -f /usr/share/games/stratagus/stargus/extracted ] && startool -V 1>/dev/null 2>&1; then

	HAS_VERSION="$(cat /usr/share/games/stratagus/stargus/extracted 2>/dev/null)"
	NEW_VERSION="$(startool -V 2>/dev/null)"

	if [ "$HAS_VERSION" = "$NEW_VERSION" ]; then
		db_set stargus/extractdata "false" || true
		db_stop || true
		exit 0
	fi

fi

db_reset stargus/extractdata || true
db_fset stargus/extractdata seen false || true
db_fset stargus/cdpath seen false || true

while true; do

	db_beginblock || true
	db_input critical stargus/extractdata || true
	db_endblock || true
	db_go || exit 10

	db_get stargus/extractdata || true
	if [ "$RET" = "false" ]; then
		break
	fi

	db_beginblock || true
	db_input critical stargus/cdpath || true
	db_endblock || true
	db_go || continue

	db_get stargus/cdpath || true
	if [ -f "$RET/install.exe" ] || [ -f "$RET/INSTALL.EXE" ]; then
		break
	fi

	db_beginblock || true
	db_input critical stargus/nodata || true
	db_endblock || true
	db_go || continue

done

db_stop || true
