#!/bin/sh

set -e

if [ "$1" = "abort-install" ] || [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
	rm -rf /usr/share/games/stratagus/stargus
	rm -rf /opt/stratagus/share/stargus
fi

#DEBHELPER#

exit 0
