#!/bin/sh

set -e

. /usr/share/debconf/confmodule

extract() {

	db_get stargus/extractdata || true

	if [ "$RET" = "true" ]; then

		db_get stargus/cdpath || true

		CDPATH=${RET}

		if [ -d "${CDPATH}" ]; then

			db_stop || true
			echo "Extracting data from ${CDPATH} to /usr/share/games/stratagus/stargus"

			cd /usr/share/games/stratagus/stargus
			/usr/games/startool ${CDPATH} /usr/share/games/stratagus/stargus
			return $?

		else

			db_stop || true
			echo "${RET} doesn't exist - can't extract Starcraft data" >&2
			return 1

		fi

	fi

	db_stop || true
	return 0

}

if [ "$1" = "configure" ]; then
	extract || exit $?
fi

#DEBHELPER#

exit 0
