AddTip("Click on NEXT TIP to cycle through all available tips. You can activate this help menu at any time by clicking on the MENU button and choosing HELP. ")
AddTip("Units can be ordered to move, attack, gather resources, or repair other units and buildings automatically. With a unit selected, right-click on the area or target where the action will be performed.")
AddTip("To toggle subtitles on or off, go to MENU. Under OPTIONS, select SOUND and click on the box marked TOGGLE SUBTITLES.")
AddTip("The Terran Refinery, Zerg Extractor and Protoss Assimilator must be constructed on top of a Vespene Geyser before any gas can be collected.")
AddTip("Most commands in the game have hot keys.  These keys are denoted by the highlighted letter in the text of the command button.")
AddTip("To restart a mission, choose END MISSION from the menu.")
AddTip("Mission objectives may be viewed at any time by choosing MISSION OBJECTIVES from the menu.")
AddTip("Any Terran Infantry units may be placed inside a Bunker. While inside a Bunker, units are shielded from attacks, but are free to return fire. To load a unit into a Bunker, select the unit and right-click on the Bunker.")
AddTip("Terran Vultures can lay Spider Mines: select a Vulture unit, then select the MINE button and designate an area of ground as the target. ")
AddTip("Queue up to five units at the same time by selecting a building, then clicking on the button of the unit you wish to queue.")
AddTip("Terran Marines and Firebats have \"Stimpack\" upgrades. Stimpacks increase a unit's attack rate and movement rate, at a cost of 10 hit points per \"stim.\"")
AddTip("In some missions, you must return specific units to a particular location, designated by a glowing Command Point Marker, called a \"Beacon.\"")
AddTip("When building a Terran Command Center, Protoss Nexus, or Zerg Hatchery, try to place it as close to resources as possible.")
AddTip("Both the Terran Wraith and Ghost have the ability to \"Cloak.\" While cloaked, they are safe from attack, unless spotted by enemy detection units.")
AddTip("Cancel any unit in a queue by clicking on its icon in the construction \"pipeline\" display.")
AddTip("Toggle the terrain information on and off in the Mini Map by pressing ~white~TAB~>.")
AddTip("Terran Dropships ferry units quickly between areas. Load Dropships by selecting one or more units, then right-clicking on the Dropship. Dropships are built at the Starport.")
AddTip("Toggle the Mini Map between Team Color Identification and Friend-or-Foe recognition modes by pressing ~white~SHIFT+TAB~>.")
AddTip("When using the MOVE command, your units will ignore enemy units as they travel to their destination.  In this way, you can also use the MOVE command to retreat.")
AddTip("Most Terran buildings can fly. Select the building and click the LIFTOFF button to fly; press the button again to select a location to land.")
AddTip("Move your units with the ATTACK command when you wish them to engage enemy forces along the way.")
AddTip("You can adjust the sound, music, and speech in the SOUND menu.")
AddTip("Take over abandoned Terran add-ons (Machine Shops, Control Towers, etc.) by landing your own buildings next to them. ")
AddTip("You can adjust the game speed, mouse speed, and other speed settings in the SPEED menu.")
AddTip("In single player games, you can speed up or slow down the game by pressing the ~white~+~> or ~white~-~> keys.")
AddTip("The Terran Nuclear Silo is an add-on to the Command Center. To launch a nuclear attack, build a nuclear missile at the silo, then use a Ghost unit to designate a target.")
AddTip("Deselect an individual unit from a group by holding down the ~white~SHIFT~> key while selecting that unit.")
AddTip("To single out a unit from within a group, either select the individual unit, or select that unit's wireframe from the status display. ")
AddTip("Missile Turrets and Science vessels reveal hidden units within their range. The Comsat station briefly reveals hidden units anywhere on the map with its Sensor Sweep.")
AddTip("Load units into a transport using the MOVE command. The transport will automatically move to meet the units.")
AddTip("Unload units from a transport by clicking the UNLOAD ALL button and selecting an unloading area. Unload an individual unit by clicking on its wireframe.")
AddTip("All Zerg buildings, except the Hatchery and Extractor, must be constructed on creep. Creep can be created by building a Hatchery or a creep colony.")
AddTip("You can designate targets for your commands (MOVE, ATTACK, GATHER, etc.) using the Mini Map.  In this way, you can send units to distant locations without having to scroll the Main Screen.")
AddTip("Click and drag in the Mini Map to rapidly scroll your view in the main screen.")
AddTip("The Zerg Hatchery can be upgraded to a Lair and eventually a Hive.  Each upgrade allows you to build additional Zerg structures.")
AddTip("To select a unit's previous group, hold down the ~white~ALT~> key while selecting that unit.")
AddTip("SAVE your game frequently. If you find yourself in a desperate situation, you can go back and LOAD your game before you got into this whole mess. ")
AddTip("Zerg Overlords can be upgraded to carry units at the Lair or Hive. Once upgraded, you can use them as transports by selecting a group of units and right-clicking on an Overlord.")
AddTip("Use the Campaign Editor, found on the Main Menu, to build your own maps and edit unit variables.")
AddTip("You can turn off unit responses in the SOUND menu.")
AddTip("Zerg Queens have the ability to \"Infest\" a severely damaged Terran Command Center. Once infested, the Command Center is now a Zerg structure capable of building Infested Terrans that explode when attacking.")
AddTip("The ~white~SHIFT~> key allows you to chain together multiple commands. Hold down the SHIFT key while issuing commands; the unit will finish each task before proceeding to the next.")
AddTip("You can use the PATROL command to setup a patrol route for your units.  While in patrol mode your units will attack any enemy units that they see.")
AddTip("Most Zerg ground units have the ability to Burrow. When Burrowed, they cannot attack or be attacked unless detected. ")
AddTip("Stationary combat units are assumed to be on guard: if they see an enemy unit they will automatically engage it.")
AddTip("Using the HOLD POSITION command, units will remain stationary, even if attacked, and attack enemy units within their range.")
AddTip("Zerg Mutalisks can be transformed into a unit called the Guardian. Once a Spire is upgraded into a Greater Spire, all Mutalisks automatically gain the ability to transform into Guardians.")
AddTip("You can setup convoys by selecting your escorts and telling them to MOVE onto the unit you want escorted.  They will then follow the designated unit.")
AddTip("To send messages to your opponent during multiplayer games, press ~white~Enter~>, type in your message and press ~white~Enter~> again.")
AddTip("Zerg Defilers have the ability to CONSUME their own units. Every unit consumed restores 50 energy points to the Defiler.")
AddTip("You can form alliances during a multiplayer game using the DIPLOMACY button on the Command Console.")
AddTip("During multiplayer games, allies achieve a shared victory only if all surviving allies have selected ALLIED VICTORY from the DIPLOMACY MENU.")
AddTip("Use the PLAGUE spell to severely damage any unit or building. It will cause up to 300 points of damage to its target, but will not kill a target.")
AddTip("In a multiplayer game, allies can share their fog of war information once all members of the alliance select SHARE VISION from the DIPLOMACY MENU.")
AddTip("Pressing ~white~CTRL-S~> will toggle the sound on or off.  ~white~CTRL-M~> will toggle the music on or off.")
AddTip("Zerg Scourge can be set on Patrol to automatically attack all air units that come near. ")
AddTip("To surrender during a campaign or multiplayer game, use the SURRENDER button in the OPTIONS menu.")
AddTip("The Zerg Queen's ENSNARE spell and The Defiler's PLAGUE spell can be cast on cloaked units to allow other units to target them.")
AddTip("Keep the path between the Command Center and available resources clear.  Obstacles slow the rate at which resources can be returned.")
AddTip("All Protoss buildings, except the Nexus, must be built within the energy field of a Pylon. ")
AddTip("To save your current position on the map, press ~white~Shift-F2~>. To recall that position at any time, press ~white~F2~>. You can save up to three views using keys F2-F4 in this manner.")
AddTip("Protoss Reavers attack by firing explosive \"Scarabs\" at their targets. To build Scarabs, select the Reaver and press the BUILD SCARABS button.")
AddTip("Different units are designed to work together and support each other. Combinations are more effective than a force composed of a single unit type.")
AddTip("Protoss Probes can build multiple buildings at one time. Once a building warp has been started, the Probe can move onto a new task.")
AddTip("Hold down ~white~CTRL~> while selecting a unit to select all units of the same type within your view.")
AddTip("Use PSIONIC STORM to damage all units in the spell's area of effect. It is devastating against a tight formation of enemy units.")
AddTip("Double-click a unit to select all units of the same type within your view.")
AddTip("Protoss Templars have the ability to transform into a powerful fighting unit called an Archon. Select two Templars and press the ARCHON WARP button to create an Archon.")
AddTip("Pressing the space bar will center the screen on the location of your last transmission.")
AddTip("Use HALLUCINATION to make multiple holograms of a single unit. Use them to scout and draw enemy fire as decoys. ")
AddTip("To save your currently selected group of units, press ~white~CTRL-1~>. To recall that group at any time, press ~white~1~>. You can save up to ten groups using keys 1 through 0 in this manner. This also works for buildings.")
AddTip("Protoss Observers are great for scouting: they remain permanently cloaked, and can detect hidden units.")
AddTip("In a multiplayer game, pressing ~white~SHIFT-ENTER~> sends your message to all players.")
AddTip("Protoss Carriers attack by launching small interceptors that swarm their target. To build Interceptors, select the Carrier and press the BUILD INTERCEPTORS button.")
AddTip("In a multiplayer game, pressing ~white~CTRL-ENTER~> sends a message that is exclusive to your allies.")
AddTip("The Protoss Arbiter cloaks all nearby units, although the Arbiter itself remains visible. Arbiters cannot cloak each other.")
AddTip("Units caught in an Arbiter's Stasis Field can neither attack nor be attacked for the duration of the spell.")
AddTip("Protoss Arbiters can use Recall to instantly teleport units to their location. ")
AddTip("In Greed and Slaughter Mutiplayer games, a leaderboard displays the current leader. Press ~white~CTRL-R~> to toggle between displaying the leader, and displaying all players.")
AddTip("Tell everyone you know to buy Starcraft.")
AddTip("")
