/*
 * startool_cd.h
 *
 *      Author: Andreas Volz
 */

#ifndef STARTOOL_CD_H_
#define STARTOOL_CD_H_

#include "startool.h"

Control CDTodo_bootstrap[] = {
  {F,0,"","install.exe" __4},
  {F,0,"","Install.exe" __4},
  {F,0,"","starcraft.mpq" __4 },
  {F,0,"","Starcraft.mpq" __4 },
  {F,0,"","StarCraft.mpq" __4 },
  {F,0,"","installer tome.mpq" __4 },
  {F,0,"","Installer Tome.mpq" __4 },
  {F,0,"","starcraft archive" __4 },
  {F,0,"","StarCraft Archive" __4 },

  {Q,0,"remove-stardat.mpq","files\\stardat.mpq" __4}
};

Control CDTodo[] = {
	// Fonts
	{N,0,"font8","files\\font\\font8.fnt" __4},
	{N,0,"font10","files\\font\\font10.fnt" __4},
	{N,0,"font12","files\\font\\font12.fnt" __4},
	{N,0,"font14","files\\font\\font14.fnt" __4},
	{N,0,"font16","files\\font\\font16.fnt" __4},
	{N,0,"font16x","files\\font\\font16x.fnt" __4},
	{N,0,"font32","files\\font\\font32.fnt" __4},
	{N,0,"font50","files\\font\\font50.fnt" __4},

	// Maps
	// if a map ends with a dot (.) then it adds .sms and .scp otherwise a dir with scenario.sms/scenario.smp
	{M,0,"maps/(2)Challenger.","multimaps\\(2)Challenger.scm" __4},
	{M,0,"maps/(2)River Crossing.","multimaps\\(2)River Crossing.scm" __4},
	{M,0,"maps/(2)Road War.","multimaps\\(2)Road War.scm" __4},
	{M,0,"maps/(2)Space Madness.","multimaps\\(2)Space Madness.scm" __4},
	{M,0,"maps/(2)The Small Divide.","multimaps\\(2)The Small Divide.scm" __4},
	{M,0,"maps/(2)Volcanis.","multimaps\\(2)Volcanis.scm" __4},
	{M,0,"maps/(3)Holy Ground.","multimaps\\(3)Holy Ground.scm" __4},
	{M,0,"maps/(3)Meltdown.","multimaps\\(3)Meltdown.scm" __4},
	{M,0,"maps/(3)Three Kingdoms.","multimaps\\(3)Three Kingdoms.scm" __4},
	{M,0,"maps/(3)Triumvirate.","multimaps\\(3)Triumvirate.scm" __4},
	{M,0,"maps/(4)Alpha Draconis.","multimaps\\(4)Alpha Draconis.scm" __4},
	{M,0,"maps/(4)Bridge Too Near.","multimaps\\(4)Bridge Too Near.scm" __4},
	{M,0,"maps/(4)Cyclone.","multimaps\\(4)Cyclone.scm" __4},
	{M,0,"maps/(4)Dark Crystal.","multimaps\\(4)Dark Crystal.scm" __4},
	{M,0,"maps/(4)Dark Star.","multimaps\\(4)Dark Star.scm" __4},
	{M,0,"maps/(4)Lost Civilization.","multimaps\\(4)Lost Civilization.scm" __4},
	{M,0,"maps/(4)Opposing City States '98.","multimaps\\(4)Opposing City States '98.scm" __4},
	{M,0,"maps/(4)Orbital Relay.","multimaps\\(4)Orbital Relay.scm" __4},
	{M,0,"maps/(4)Power Lines.","multimaps\\(4)Power Lines.scm" __4},
	{M,0,"maps/(4)Ruins of the Ancients.","multimaps\\(4)Ruins of the Ancients.scm" __4},
	{M,0,"maps/(4)Tarsonis Orbital.","multimaps\\(4)Tarsonis Orbital.scm" __4},
	{M,0,"maps/(5)Diablo.","multimaps\\(5)Diablo.scm" __4},
	{M,0,"maps/(5)Island Hop.","multimaps\\(5)Island Hop.scm" __4},
	{M,0,"maps/(5)Jeweled River.","multimaps\\(5)Jeweled River.scm" __4},
	{M,0,"maps/(5)Sherwood Forest.","multimaps\\(5)Sherwood Forest.scm" __4},
	{M,0,"maps/(6)Ground Zero.","multimaps\\(6)Ground Zero.scm" __4},
	{M,0,"maps/(6)Hidden Shrine.","multimaps\\(6)Hidden Shrine.scm" __4},
	{M,0,"maps/(6)New Gettysburg.","multimaps\\(6)New Gettysburg.scm" __4},
	{M,0,"maps/(7)Continental Divide.","multimaps\\(7)Continental Divide.scm" __4},
	{M,0,"maps/(7)River War.","multimaps\\(7)River War.scm" __4},
	{M,0,"maps/(8)Bridge to Bridge '98.","multimaps\\(8)Bridge to Bridge '98.scm" __4},
	{M,0,"maps/(8)Char Magma.","multimaps\\(8)Char Magma.scm" __4},
	{M,0,"maps/(8)Homeworld.","multimaps\\(8)Homeworld.scm" __4},
	{M,0,"maps/(8)Killing Fields.","multimaps\\(8)Killing Fields.scm" __4},
	{M,0,"maps/(8)Orbital Death.","multimaps\\(8)Orbital Death.scm" __4},
	{M,0,"maps/(8)Plains of Snow '98.","multimaps\\(8)Plains of Snow '98.scm" __4},
	{M,0,"maps/(8)Station Unrest.","multimaps\\(8)Station Unrest.scm" __4},
	{M,0,"maps/(8)The Hunters.","multimaps\\(8)The Hunters.scm" __4},

	// some maps from subdirs
	{M,0,"maps/campaign/(1)enslavers01.","multimaps\\campaign\\(1)enslavers01.scm" __4},
	{M,0,"maps/campaign/(1)enslavers02a.","multimaps\\campaign\\(1)enslavers02a.scm" __4},
	{M,0,"maps/campaign/(1)enslavers02b.","multimaps\\campaign\\(1)enslavers02b.scm" __4},
	{M,0,"maps/campaign/(1)enslavers03a.","multimaps\\campaign\\(1)enslavers03a.scm" __4},
	{M,0,"maps/campaign/(1)enslavers03b.","multimaps\\campaign\\(1)enslavers03b.scm" __4},

	{M,0,"maps/ladder/(2)discovery.","multimaps\\ladder\\(2)discovery.scm" __4},
	{M,0,"maps/ladder/(2)river styx.","multimaps\\ladder\\(2)river styx.scm" __4},
	{M,0,"maps/ladder/(2)solar station.","multimaps\\ladder\\(2)solar station.scm" __4},
	{M,0,"maps/ladder/(4)crusader.","multimaps\\ladder\\(4)crusader.scm" __4},
	{M,0,"maps/ladder/(4)dire straits.","multimaps\\ladder\\(4)dire straits.scm" __4},
	{M,0,"maps/ladder/(4)rivalry.","multimaps\\ladder\\(4)rivalry.scm" __4},
	{M,0,"maps/ladder/(4)lost temple.","multimaps\\ladder\\(4)lost temple.scm" __4},

	{M,0,"maps/scenario/(2)pro bowl.","multimaps\\scenario\\(2)pro bowl.scm" __4},
	{M,0,"maps/scenario/(2)wakka wakka.","multimaps\\scenario\\(2)wakka wakka.scm" __4},
	{M,0,"maps/scenario/(3)defenders of the galaxy.","multimaps\\scenario\\(3)defenders of the galaxy.scm" __4},
	{M,0,"maps/scenario/(4)king of the hill.","multimaps\\scenario\\(4)king of the hill.scm" __4},
	{M,0,"maps/scenario/(4)old faithful.","multimaps\\scenario\\(4)old faithful.scm" __4},
	{M,0,"maps/scenario/(4)steal the bacon.","multimaps\\scenario\\(4)steal the bacon.scm" __4},
	{M,0,"maps/scenario/(4)zergling round-up.","multimaps\\scenario\\(4)zergling round-up.scm" __4},
	{M,0,"maps/scenario/(4)zoo keeper.","multimaps\\scenario\\(4)zoo keeper.scm" __4},
	{M,0,"maps/scenario/(5)race of death.","multimaps\\scenario\\(5)race of death.scm" __4},
	{M,0,"maps/scenario/(8)starcraft fortress.","multimaps\\scenario\\(8)starcraft fortress.scm" __4},

	// Terran Campaigns
	{H,0,"campaigns/terran/palta-blank","glue\\PalTA\\Blank.pcx",0 __3},
	{H,0,"campaigns/terran/palta-terrana","glue\\palta\\TerranA.pcx",0 __3},
	{H,0,"campaigns/terran/palta-tfont","glue\\palta\\tfont.pcx",0 __3},
	{H,0,"campaigns/terran/paltb-blank","glue\\paltb\\Blank.pcx",0 __3},
	{H,0,"campaigns/terran/paltb-terranb","glue\\paltb\\TerranB.pcx",0 __3},
	{H,0,"campaigns/terran/paltb-tfont","glue\\paltb\\tfont.pcx",0 __3},
	{H,0,"campaigns/terran/paltc-blank","glue\\paltc\\Blank.pcx",0 __3},
	{H,0,"campaigns/terran/paltc-terranc","glue\\paltc\\TerranC.pcx",0 __3},
	{H,0,"campaigns/terran/paltc-tfont","glue\\paltc\\tfont.pcx",0 __3},

	{L,0,"campaigns/terran/tutorial/","campaign\\terran\\tutorial\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/tutorial/ComBeep0","campaign\\terran\\tutorial\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0B00tad","campaign\\terran\\tutorial\\staredit\\wav\\T0B00tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0B01tad","campaign\\terran\\tutorial\\staredit\\wav\\T0B01tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0B02tad","campaign\\terran\\tutorial\\staredit\\wav\\T0B02tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0B03tad","campaign\\terran\\tutorial\\staredit\\wav\\T0B03tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0B04tad","campaign\\terran\\tutorial\\staredit\\wav\\T0B04tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0B05tad","campaign\\terran\\tutorial\\staredit\\wav\\T0B05tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0B60tad","campaign\\terran\\tutorial\\staredit\\wav\\T0B60tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M00tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M00tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M01tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M01tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M02tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M02tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M03tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M03tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M04tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M04tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M05tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M05tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M06tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M06tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M07tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M07tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M21tad","campaign\\terran\\tutorial\\staredit\\wav\\T0M21tad.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M30tma","campaign\\terran\\tutorial\\staredit\\wav\\T0M30tma.wav" __4},
	{W,0,"campaigns/terran/tutorial/T0M31tma","campaign\\terran\\tutorial\\staredit\\wav\\T0M31tma.wav" __4},
	{W,0,"campaigns/terran/tutorial/TSCYes01","campaign\\terran\\tutorial\\staredit\\wav\\TSCYes01.wav" __4},
	{L,0,"campaigns/terran/01/","campaign\\terran\\terran01\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/01/ComBeep0","campaign\\terran\\terran01\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/01/ComBeep1","campaign\\terran\\terran01\\staredit\\wav\\ComBeep1.wav" __4},
	{W,0,"campaigns/terran/01/T0M20tad","campaign\\terran\\terran01\\staredit\\wav\\T0M20tad.wav" __4},
	{W,0,"campaigns/terran/01/T1B00tad","campaign\\terran\\terran01\\staredit\\wav\\T1B00tad.wav" __4},
	{W,0,"campaigns/terran/01/T1B01udu","campaign\\terran\\terran01\\staredit\\wav\\T1B01udu.wav" __4},
	{W,0,"campaigns/terran/01/T1B02tad","campaign\\terran\\terran01\\staredit\\wav\\T1B02tad.wav" __4},
	{W,0,"campaigns/terran/01/T1M01uci","campaign\\terran\\terran01\\staredit\\wav\\T1M01uci.wav" __4},
	{W,0,"campaigns/terran/01/T1M20ura","campaign\\terran\\terran01\\staredit\\wav\\T1M20ura.wav" __4},
	{L,0,"campaigns/terran/02/","campaign\\terran\\terran02\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/02/ComBeep0","campaign\\terran\\terran02\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/02/ComBeep1","campaign\\terran\\terran02\\staredit\\wav\\ComBeep1.wav" __4},
	{W,0,"campaigns/terran/02/T2B00tad","campaign\\terran\\terran02\\staredit\\wav\\T2B00tad.wav" __4},
	{W,0,"campaigns/terran/02/T2B01ura","campaign\\terran\\terran02\\staredit\\wav\\T2B01ura.wav" __4},
	{W,0,"campaigns/terran/02/T2B02tad","campaign\\terran\\terran02\\staredit\\wav\\T2B02tad.wav" __4},
	{W,0,"campaigns/terran/02/T2B03udu","campaign\\terran\\terran02\\staredit\\wav\\T2B03udu.wav" __4},
	{W,0,"campaigns/terran/02/T2B04ura","campaign\\terran\\terran02\\staredit\\wav\\T2B04ura.wav" __4},
	{W,0,"campaigns/terran/02/T2M00ura","campaign\\terran\\terran02\\staredit\\wav\\T2M00ura.wav" __4},
	{W,0,"campaigns/terran/02/T2M20ura","campaign\\terran\\terran02\\staredit\\wav\\T2M20ura.wav" __4},
	{W,0,"campaigns/terran/02/T2M30uci","campaign\\terran\\terran02\\staredit\\wav\\T2M30uci.wav" __4},
	{W,0,"campaigns/terran/02/T2M40ura","campaign\\terran\\terran02\\staredit\\wav\\T2M40ura.wav" __4},
	{W,0,"campaigns/terran/02/T2M60ftb","campaign\\terran\\terran02\\staredit\\wav\\T2M60ftb.wav" __4},
	{W,0,"campaigns/terran/02/T2M60tma","campaign\\terran\\terran02\\staredit\\wav\\T2M60tma.wav" __4},
	{W,0,"campaigns/terran/02/T2M60ura","campaign\\terran\\terran02\\staredit\\wav\\T2M60ura.wav" __4},
	{W,0,"campaigns/terran/02/T2M80udu","campaign\\terran\\terran02\\staredit\\wav\\T2M80udu.wav" __4},
	{W,0,"campaigns/terran/02/T2M81ura","campaign\\terran\\terran02\\staredit\\wav\\T2M81ura.wav" __4},
	{W,0,"campaigns/terran/02/T2M82udu","campaign\\terran\\terran02\\staredit\\wav\\T2M82udu.wav" __4},
	{W,0,"campaigns/terran/02/T2M83ura","campaign\\terran\\terran02\\staredit\\wav\\T2M83ura.wav" __4},
	{W,0,"campaigns/terran/02/TCB02tad","campaign\\terran\\terran02\\staredit\\wav\\TCB02tad.wav" __4},
	{W,0,"campaigns/terran/02/tdrTra01","campaign\\terran\\terran02\\staredit\\wav\\tdrTra01.wav" __4},
	{W,0,"campaigns/terran/02/tfbRdy00","campaign\\terran\\terran02\\staredit\\wav\\tfbRdy00.wav" __4},
	{L,0,"campaigns/terran/03/","campaign\\terran\\terran03\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/03/ComBeep0","campaign\\terran\\terran03\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/03/T0M40tvu","campaign\\terran\\terran03\\staredit\\wav\\T0M40tvu.wav" __4},
	{W,0,"campaigns/terran/03/T3B00tad","campaign\\terran\\terran03\\staredit\\wav\\T3B00tad.wav" __4},
	{W,0,"campaigns/terran/03/T3B01udu","campaign\\terran\\terran03\\staredit\\wav\\T3B01udu.wav" __4},
	{W,0,"campaigns/terran/03/T3B02tad","campaign\\terran\\terran03\\staredit\\wav\\T3B02tad.wav" __4},
	{W,0,"campaigns/terran/03/T3B03ume","campaign\\terran\\terran03\\staredit\\wav\\T3B03ume.wav" __4},
	{W,0,"campaigns/terran/03/T3B04ume","campaign\\terran\\terran03\\staredit\\wav\\T3B04ume.wav" __4},
	{W,0,"campaigns/terran/03/T3B05tad","campaign\\terran\\terran03\\staredit\\wav\\T3B05tad.wav" __4},
	{W,0,"campaigns/terran/03/T3M00tad","campaign\\terran\\terran03\\staredit\\wav\\T3M00tad.wav" __4},
	{W,0,"campaigns/terran/03/T3M20tad","campaign\\terran\\terran03\\staredit\\wav\\T3M20tad.wav" __4},
	{W,0,"campaigns/terran/03/T3M21tad","campaign\\terran\\terran03\\staredit\\wav\\T3M21tad.wav" __4},
	{W,0,"campaigns/terran/03/T3M60tad","campaign\\terran\\terran03\\staredit\\wav\\T3M60tad.wav" __4},
	{W,0,"campaigns/terran/03/T3M70tad","campaign\\terran\\terran03\\staredit\\wav\\T3M70tad.wav" __4},
	{W,0,"campaigns/terran/03/T3M80tad","campaign\\terran\\terran03\\staredit\\wav\\T3M80tad.wav" __4},
	{W,0,"campaigns/terran/03/T3M90tma","campaign\\terran\\terran03\\staredit\\wav\\T3M90tma.wav" __4},
	{W,0,"campaigns/terran/03/TDrYes04","campaign\\terran\\terran03\\staredit\\wav\\TDrYes04.wav" __4},
	{L,0,"campaigns/terran/04/","campaign\\terran\\terran04\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/04/ComBeep0","campaign\\terran\\terran04\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/04/ComBeep1","campaign\\terran\\terran04\\staredit\\wav\\ComBeep1.wav" __4},
	{W,0,"campaigns/terran/04/P6M00tad","campaign\\terran\\terran04\\staredit\\wav\\P6M00tad.wav" __4},
	{W,0,"campaigns/terran/04/PPwrDown","campaign\\terran\\terran04\\staredit\\wav\\PPwrDown.wav" __4},
	{W,0,"campaigns/terran/04/T4B00tad","campaign\\terran\\terran04\\staredit\\wav\\T4B00tad.wav" __4},
	{W,0,"campaigns/terran/04/T4B01ura","campaign\\terran\\terran04\\staredit\\wav\\T4B01ura.wav" __4},
	{W,0,"campaigns/terran/04/T4B02ume","campaign\\terran\\terran04\\staredit\\wav\\T4B02ume.wav" __4},
	{W,0,"campaigns/terran/04/T4B03ume","campaign\\terran\\terran04\\staredit\\wav\\T4B03ume.wav" __4},
	{W,0,"campaigns/terran/04/T4B04ura","campaign\\terran\\terran04\\staredit\\wav\\T4B04ura.wav" __4},
	{W,0,"campaigns/terran/04/T4M00uci","campaign\\terran\\terran04\\staredit\\wav\\T4M00uci.wav" __4},
	{W,0,"campaigns/terran/04/T4M00ura","campaign\\terran\\terran04\\staredit\\wav\\T4M00ura.wav" __4},
	{W,0,"campaigns/terran/04/T4M01ume","campaign\\terran\\terran04\\staredit\\wav\\T4M01ume.wav" __4},
	{W,0,"campaigns/terran/04/T4M20uci","campaign\\terran\\terran04\\staredit\\wav\\T4M20uci.wav" __4},
	{W,0,"campaigns/terran/04/T4M20ura","campaign\\terran\\terran04\\staredit\\wav\\T4M20ura.wav" __4},
	{W,0,"campaigns/terran/04/T4M30uma","campaign\\terran\\terran04\\staredit\\wav\\T4M30uma.wav" __4},
	{W,0,"campaigns/terran/04/T4M70tad","campaign\\terran\\terran04\\staredit\\wav\\T4M70tad.wav" __4},
	{W,0,"campaigns/terran/04/Z5M00tad","campaign\\terran\\terran04\\staredit\\wav\\Z5M00tad.wav" __4},
	{L,0,"campaigns/terran/05/","campaign\\terran\\terran05\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/05/ComBeep0","campaign\\terran\\terran05\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/05/T5B00ura","campaign\\terran\\terran05\\staredit\\wav\\T5B00ura.wav" __4},
	{W,0,"campaigns/terran/05/T5B01tad","campaign\\terran\\terran05\\staredit\\wav\\T5B01tad.wav" __4},
	{W,0,"campaigns/terran/05/T5B02ume","campaign\\terran\\terran05\\staredit\\wav\\T5B02ume.wav" __4},
	{W,0,"campaigns/terran/05/T5B03uke","campaign\\terran\\terran05\\staredit\\wav\\T5B03uke.wav" __4},
	{W,0,"campaigns/terran/05/T5B04ume","campaign\\terran\\terran05\\staredit\\wav\\T5B04ume.wav" __4},
	{W,0,"campaigns/terran/05/T5M00uke","campaign\\terran\\terran05\\staredit\\wav\\T5M00uke.wav" __4},
	{W,0,"campaigns/terran/05/T5M01ura","campaign\\terran\\terran05\\staredit\\wav\\T5M01ura.wav" __4},
	{W,0,"campaigns/terran/05/T5M02uke","campaign\\terran\\terran05\\staredit\\wav\\T5M02uke.wav" __4},
	{W,0,"campaigns/terran/05/T5M03ura","campaign\\terran\\terran05\\staredit\\wav\\T5M03ura.wav" __4},
	{W,0,"campaigns/terran/05/T5M04uke","campaign\\terran\\terran05\\staredit\\wav\\T5M04uke.wav" __4},
	{W,0,"campaigns/terran/05/T5M20uke","campaign\\terran\\terran05\\staredit\\wav\\T5M20uke.wav" __4},
	{W,0,"campaigns/terran/05/T5M40uma","campaign\\terran\\terran05\\staredit\\wav\\T5M40uma.wav" __4},
	{W,0,"campaigns/terran/05/T5M41uke","campaign\\terran\\terran05\\staredit\\wav\\T5M41uke.wav" __4},
	{W,0,"campaigns/terran/05/T5M42tad","campaign\\terran\\terran05\\staredit\\wav\\T5M42tad.wav" __4},
	{W,0,"campaigns/terran/05/T5M43uke","campaign\\terran\\terran05\\staredit\\wav\\T5M43uke.wav" __4},
	{W,0,"campaigns/terran/05/T5M44uma","campaign\\terran\\terran05\\staredit\\wav\\T5M44uma.wav" __4},
	{L,0,"campaigns/terran/06/","campaign\\terran\\terran06\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/06/ComBeep0","campaign\\terran\\terran06\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/06/T6B00tad","campaign\\terran\\terran06\\staredit\\wav\\T6B00tad.wav" __4},
	{W,0,"campaigns/terran/06/T6B01udu","campaign\\terran\\terran06\\staredit\\wav\\T6B01udu.wav" __4},
	{W,0,"campaigns/terran/06/T6B02ura","campaign\\terran\\terran06\\staredit\\wav\\T6B02ura.wav" __4},
	{W,0,"campaigns/terran/06/T6B03ume","campaign\\terran\\terran06\\staredit\\wav\\T6B03ume.wav" __4},
	{W,0,"campaigns/terran/06/T6B04ura","campaign\\terran\\terran06\\staredit\\wav\\T6B04ura.wav" __4},
	{W,0,"campaigns/terran/06/T6B05uke","campaign\\terran\\terran06\\staredit\\wav\\T6B05uke.wav" __4},
	{W,0,"campaigns/terran/06/T6B06ume","campaign\\terran\\terran06\\staredit\\wav\\T6B06ume.wav" __4},
	{W,0,"campaigns/terran/06/T6B07uke","campaign\\terran\\terran06\\staredit\\wav\\T6B07uke.wav" __4},
	{W,0,"campaigns/terran/06/T6B08ume","campaign\\terran\\terran06\\staredit\\wav\\T6B08ume.wav" __4},
	{W,0,"campaigns/terran/06/T6B09uke","campaign\\terran\\terran06\\staredit\\wav\\T6B09uke.wav" __4},
	{W,0,"campaigns/terran/06/T6B10ura","campaign\\terran\\terran06\\staredit\\wav\\T6B10ura.wav" __4},
	{W,0,"campaigns/terran/06/T6M00ura","campaign\\terran\\terran06\\staredit\\wav\\T6M00ura.wav" __4},
	{W,0,"campaigns/terran/06/T6M20udu","campaign\\terran\\terran06\\staredit\\wav\\T6M20udu.wav" __4},
	{W,0,"campaigns/terran/06/T6M21ura","campaign\\terran\\terran06\\staredit\\wav\\T6M21ura.wav" __4},
	{W,0,"campaigns/terran/06/T6M22ume","campaign\\terran\\terran06\\staredit\\wav\\T6M22ume.wav" __4},
	{W,0,"campaigns/terran/06/T6M23udu","campaign\\terran\\terran06\\staredit\\wav\\T6M23udu.wav" __4},
	{W,0,"campaigns/terran/06/T6M24ume","campaign\\terran\\terran06\\staredit\\wav\\T6M24ume.wav" __4},
	{W,0,"campaigns/terran/06/T6M25udu","campaign\\terran\\terran06\\staredit\\wav\\T6M25udu.wav" __4},
	{W,0,"campaigns/terran/06/T6M26ume","campaign\\terran\\terran06\\staredit\\wav\\T6M26ume.wav" __4},
	{W,0,"campaigns/terran/06/T6M27udu","campaign\\terran\\terran06\\staredit\\wav\\T6M27udu.wav" __4},
	{W,0,"campaigns/terran/06/T6M28ume","campaign\\terran\\terran06\\staredit\\wav\\T6M28ume.wav" __4},
	{W,0,"campaigns/terran/06/T6M29ura","campaign\\terran\\terran06\\staredit\\wav\\T6M29ura.wav" __4},
	{W,0,"campaigns/terran/06/T6M30ume","campaign\\terran\\terran06\\staredit\\wav\\T6M30ume.wav" __4},
	{L,0,"campaigns/terran/07/","campaign\\terran\\terran07\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/07/ComBeep0","campaign\\terran\\terran07\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/07/T7B00tad","campaign\\terran\\terran07\\staredit\\wav\\T7B00tad.wav" __4},
	{W,0,"campaigns/terran/07/T7B01ura","campaign\\terran\\terran07\\staredit\\wav\\T7B01ura.wav" __4},
	{W,0,"campaigns/terran/07/T7B02udu","campaign\\terran\\terran07\\staredit\\wav\\T7B02udu.wav" __4},
	{W,0,"campaigns/terran/07/T7B03ura","campaign\\terran\\terran07\\staredit\\wav\\T7B03ura.wav" __4},
	{W,0,"campaigns/terran/07/T7B04udu","campaign\\terran\\terran07\\staredit\\wav\\T7B04udu.wav" __4},
	{W,0,"campaigns/terran/07/T7B05uke","campaign\\terran\\terran07\\staredit\\wav\\T7B05uke.wav" __4},
	{W,0,"campaigns/terran/07/T7B06ume","campaign\\terran\\terran07\\staredit\\wav\\T7B06ume.wav" __4},
	{W,0,"campaigns/terran/07/T7B07uke","campaign\\terran\\terran07\\staredit\\wav\\T7B07uke.wav" __4},
	{W,0,"campaigns/terran/07/T7B08ume","campaign\\terran\\terran07\\staredit\\wav\\T7B08ume.wav" __4},
	{W,0,"campaigns/terran/07/T7M00udu","campaign\\terran\\terran07\\staredit\\wav\\T7M00udu.wav" __4},
	{W,0,"campaigns/terran/07/T7M01ura","campaign\\terran\\terran07\\staredit\\wav\\T7M01ura.wav" __4},
	{W,0,"campaigns/terran/07/T7M02udu","campaign\\terran\\terran07\\staredit\\wav\\T7M02udu.wav" __4},
	{W,0,"campaigns/terran/07/T7M03ura","campaign\\terran\\terran07\\staredit\\wav\\T7M03ura.wav" __4},
	{W,0,"campaigns/terran/07/T7M20tad","campaign\\terran\\terran07\\staredit\\wav\\T7M20tad.wav" __4},
	{W,0,"campaigns/terran/07/T7M21ura","campaign\\terran\\terran07\\staredit\\wav\\T7M21ura.wav" __4},
	{W,0,"campaigns/terran/07/T7M22uta","campaign\\terran\\terran07\\staredit\\wav\\T7M22uta.wav" __4},
	{W,0,"campaigns/terran/07/T7M23ura","campaign\\terran\\terran07\\staredit\\wav\\T7M23ura.wav" __4},
	{W,0,"campaigns/terran/07/T7M24uta","campaign\\terran\\terran07\\staredit\\wav\\T7M24uta.wav" __4},
	{L,0,"campaigns/terran/08/","campaign\\terran\\terran08\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/08/ComBeep0","campaign\\terran\\terran08\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/08/T8B00tad","campaign\\terran\\terran08\\staredit\\wav\\T8B00tad.wav" __4},
	{W,0,"campaigns/terran/08/T8B01ume","campaign\\terran\\terran08\\staredit\\wav\\T8B01ume.wav" __4},
	{W,0,"campaigns/terran/08/T8B02uke","campaign\\terran\\terran08\\staredit\\wav\\T8B02uke.wav" __4},
	{W,0,"campaigns/terran/08/T8B03ura","campaign\\terran\\terran08\\staredit\\wav\\T8B03ura.wav" __4},
	{W,0,"campaigns/terran/08/T8B04uke","campaign\\terran\\terran08\\staredit\\wav\\T8B04uke.wav" __4},
	{W,0,"campaigns/terran/08/T8B05ume","campaign\\terran\\terran08\\staredit\\wav\\T8B05ume.wav" __4},
	{W,0,"campaigns/terran/08/T8B06ura","campaign\\terran\\terran08\\staredit\\wav\\T8B06ura.wav" __4},
	{W,0,"campaigns/terran/08/T8B07ume","campaign\\terran\\terran08\\staredit\\wav\\T8B07ume.wav" __4},
	{W,0,"campaigns/terran/08/T8B08ume","campaign\\terran\\terran08\\staredit\\wav\\T8B08ume.wav" __4},
	{W,0,"campaigns/terran/08/T8B09ume","campaign\\terran\\terran08\\staredit\\wav\\T8B09ume.wav" __4},
	{W,0,"campaigns/terran/08/T8M00uke","campaign\\terran\\terran08\\staredit\\wav\\T8M00uke.wav" __4},
	{W,0,"campaigns/terran/08/T8M01ume","campaign\\terran\\terran08\\staredit\\wav\\T8M01ume.wav" __4},
	{W,0,"campaigns/terran/08/T8M02uke","campaign\\terran\\terran08\\staredit\\wav\\T8M02uke.wav" __4},
	{W,0,"campaigns/terran/08/T8M40uke","campaign\\terran\\terran08\\staredit\\wav\\T8M40uke.wav" __4},
	{W,0,"campaigns/terran/08/T8m41ume","campaign\\terran\\terran08\\staredit\\wav\\T8m41ume.wav" __4},
	{L,0,"campaigns/terran/09/","campaign\\terran\\terran09\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/09/ComBeep0","campaign\\terran\\terran09\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/09/T9B00tad","campaign\\terran\\terran09\\staredit\\wav\\T9B00tad.wav" __4},
	{W,0,"campaigns/terran/09/T9B01ume","campaign\\terran\\terran09\\staredit\\wav\\T9B01ume.wav" __4},
	{W,0,"campaigns/terran/09/T9B02udu","campaign\\terran\\terran09\\staredit\\wav\\T9B02udu.wav" __4},
	{W,0,"campaigns/terran/09/T9B03ura","campaign\\terran\\terran09\\staredit\\wav\\T9B03ura.wav" __4},
	{W,0,"campaigns/terran/09/T9B04udu","campaign\\terran\\terran09\\staredit\\wav\\T9B04udu.wav" __4},
	{W,0,"campaigns/terran/09/T9B05ura","campaign\\terran\\terran09\\staredit\\wav\\T9B05ura.wav" __4},
	{W,0,"campaigns/terran/09/T9M00ura","campaign\\terran\\terran09\\staredit\\wav\\T9M00ura.wav" __4},
	{W,0,"campaigns/terran/09/T9M20udu","campaign\\terran\\terran09\\staredit\\wav\\T9M20udu.wav" __4},
	{W,0,"campaigns/terran/09/TAM00udu","campaign\\terran\\terran09\\staredit\\wav\\TAM00udu.wav" __4},
	{W,0,"campaigns/terran/09/TAM01uke","campaign\\terran\\terran09\\staredit\\wav\\TAM01uke.wav" __4},
	{W,0,"campaigns/terran/09/TAM02ume","campaign\\terran\\terran09\\staredit\\wav\\TAM02ume.wav" __4},
	{W,0,"campaigns/terran/09/TAM03uke","campaign\\terran\\terran09\\staredit\\wav\\TAM03uke.wav" __4},
	{W,0,"campaigns/terran/09/TAM04ura","campaign\\terran\\terran09\\staredit\\wav\\TAM04ura.wav" __4},
	{W,0,"campaigns/terran/09/TAM05ume","campaign\\terran\\terran09\\staredit\\wav\\TAM05ume.wav" __4},
	{L,0,"campaigns/terran/10/","campaign\\terran\\terran10\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/10/ComBeep0","campaign\\terran\\terran10\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/10/TAB00tad","campaign\\terran\\terran10\\staredit\\wav\\TAB00tad.wav" __4},
	{W,0,"campaigns/terran/10/TAB01ume","campaign\\terran\\terran10\\staredit\\wav\\TAB01ume.wav" __4},
	{W,0,"campaigns/terran/10/TAB02ume","campaign\\terran\\terran10\\staredit\\wav\\TAB02ume.wav" __4},
	{W,0,"campaigns/terran/10/TAB03uke","campaign\\terran\\terran10\\staredit\\wav\\TAB03uke.wav" __4},
	{W,0,"campaigns/terran/10/TAB04udu","campaign\\terran\\terran10\\staredit\\wav\\TAB04udu.wav" __4},
	{W,0,"campaigns/terran/10/TAB05ura","campaign\\terran\\terran10\\staredit\\wav\\TAB05ura.wav" __4},
	{W,0,"campaigns/terran/10/TAB06udu","campaign\\terran\\terran10\\staredit\\wav\\TAB06udu.wav" __4},
	{W,0,"campaigns/terran/10/TAM00udu","campaign\\terran\\terran10\\staredit\\wav\\TAM00udu.wav" __4},
	{W,0,"campaigns/terran/10/TAM01uke","campaign\\terran\\terran10\\staredit\\wav\\TAM01uke.wav" __4},
	{W,0,"campaigns/terran/10/TAM02ume","campaign\\terran\\terran10\\staredit\\wav\\TAM02ume.wav" __4},
	{W,0,"campaigns/terran/10/TAM03uke","campaign\\terran\\terran10\\staredit\\wav\\TAM03uke.wav" __4},
	{W,0,"campaigns/terran/10/TAM04ura","campaign\\terran\\terran10\\staredit\\wav\\TAM04ura.wav" __4},
	{W,0,"campaigns/terran/10/TAM05ume","campaign\\terran\\terran10\\staredit\\wav\\TAM05ume.wav" __4},
	{L,0,"campaigns/terran/11/","campaign\\terran\\terran11\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/11/ComBeep0","campaign\\terran\\terran11\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/11/TBB00tad","campaign\\terran\\terran11\\staredit\\wav\\TBB00tad.wav" __4},
	{W,0,"campaigns/terran/11/TBB01ume","campaign\\terran\\terran11\\staredit\\wav\\TBB01ume.wav" __4},
	{W,0,"campaigns/terran/11/TBB02ura","campaign\\terran\\terran11\\staredit\\wav\\TBB02ura.wav" __4},
	{W,0,"campaigns/terran/11/TBB03ume","campaign\\terran\\terran11\\staredit\\wav\\TBB03ume.wav" __4},
	{W,0,"campaigns/terran/11/TBB04ura","campaign\\terran\\terran11\\staredit\\wav\\TBB04ura.wav" __4},
	{W,0,"campaigns/terran/11/TBB05uke","campaign\\terran\\terran11\\staredit\\wav\\TBB05uke.wav" __4},
	{W,0,"campaigns/terran/11/TBB06ura","campaign\\terran\\terran11\\staredit\\wav\\TBB06ura.wav" __4},
	{W,0,"campaigns/terran/11/TBM00ura","campaign\\terran\\terran11\\staredit\\wav\\TBM00ura.wav" __4},
	{W,0,"campaigns/terran/11/TBM01uke","campaign\\terran\\terran11\\staredit\\wav\\TBM01uke.wav" __4},
	{W,0,"campaigns/terran/11/TBM04ura","campaign\\terran\\terran11\\staredit\\wav\\TBM04ura.wav" __4},
	{W,0,"campaigns/terran/11/TBM20ume","campaign\\terran\\terran11\\staredit\\wav\\TBM20ume.wav" __4},
	{W,0,"campaigns/terran/11/TBM21uma","campaign\\terran\\terran11\\staredit\\wav\\TBM21uma.wav" __4},
	{W,0,"campaigns/terran/11/TBM40tad","campaign\\terran\\terran11\\staredit\\wav\\TBM40tad.wav" __4},
	{W,0,"campaigns/terran/11/TBM41uke","campaign\\terran\\terran11\\staredit\\wav\\TBM41uke.wav" __4},
	{W,0,"campaigns/terran/11/TBM42ume","campaign\\terran\\terran11\\staredit\\wav\\TBM42ume.wav" __4},
	{W,0,"campaigns/terran/11/TBM43ura","campaign\\terran\\terran11\\staredit\\wav\\TBM43ura.wav" __4},
	{W,0,"campaigns/terran/11/TBM44ume","campaign\\terran\\terran11\\staredit\\wav\\TBM44ume.wav" __4},
	{W,0,"campaigns/terran/11/TBM45uke","campaign\\terran\\terran11\\staredit\\wav\\TBM45uke.wav" __4},
	{W,0,"campaigns/terran/11/TBM46ura","campaign\\terran\\terran11\\staredit\\wav\\TBM46ura.wav" __4},
	{W,0,"campaigns/terran/11/TBM47ume","campaign\\terran\\terran11\\staredit\\wav\\TBM47ume.wav" __4},
	{W,0,"campaigns/terran/11/TBm48uke","campaign\\terran\\terran11\\staredit\\wav\\TBm48uke.wav" __4},
	{L,0,"campaigns/terran/12/","campaign\\terran\\terran12\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/terran/12/ComBeep0","campaign\\terran\\terran12\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/terran/12/TCB00tad","campaign\\terran\\terran12\\staredit\\wav\\TCB00tad.wav" __4},
	{W,0,"campaigns/terran/12/TCB01ura","campaign\\terran\\terran12\\staredit\\wav\\TCB01ura.wav" __4},
	{W,0,"campaigns/terran/12/TCB02tad","campaign\\terran\\terran12\\staredit\\wav\\TCB02tad.wav" __4},
	{W,0,"campaigns/terran/12/TCB03ume","campaign\\terran\\terran12\\staredit\\wav\\TCB03ume.wav" __4},
	{W,0,"campaigns/terran/12/TCB04ura","campaign\\terran\\terran12\\staredit\\wav\\TCB04ura.wav" __4},
	{W,0,"campaigns/terran/12/TCB05ume","campaign\\terran\\terran12\\staredit\\wav\\TCB05ume.wav" __4},
	{W,0,"campaigns/terran/12/TCB06ura","campaign\\terran\\terran12\\staredit\\wav\\TCB06ura.wav" __4},
	{W,0,"campaigns/terran/12/TCB07ume","campaign\\terran\\terran12\\staredit\\wav\\TCB07ume.wav" __4},
	{W,0,"campaigns/terran/12/TCB08tad","campaign\\terran\\terran12\\staredit\\wav\\TCB08tad.wav" __4},
	{W,0,"campaigns/terran/12/TCB09ura","campaign\\terran\\terran12\\staredit\\wav\\TCB09ura.wav" __4},
	{W,0,"campaigns/terran/12/TCM00ura","campaign\\terran\\terran12\\staredit\\wav\\TCM00ura.wav" __4},
	{W,0,"campaigns/terran/12/TCM01ura","campaign\\terran\\terran12\\staredit\\wav\\TCM01ura.wav" __4},
	{W,0,"campaigns/terran/12/TCM20tad","campaign\\terran\\terran12\\staredit\\wav\\TCM20tad.wav" __4},

	{E,0,"campaigns/terran/EstT0t.txt","rez\\EstT0t.txt" __4},
	{E,0,"campaigns/terran/EstT01.txt","rez\\EstT01.txt" __4},
	{E,0,"campaigns/terran/EstT02.txt","rez\\EstT02.txt" __4},
	{E,0,"campaigns/terran/EstT03.txt","rez\\EstT03.txt" __4},
	{E,0,"campaigns/terran/EstT04.txt","rez\\EstT04.txt" __4},
	{E,0,"campaigns/terran/EstT05.txt","rez\\EstT05.txt" __4},
	{E,0,"campaigns/terran/EstT06.txt","rez\\EstT06.txt" __4},
	{E,0,"campaigns/terran/EstT07.txt","rez\\EstT07.txt" __4},
	{E,0,"campaigns/terran/EstT08.txt","rez\\EstT08.txt" __4},
	{E,0,"campaigns/terran/EstT09.txt","rez\\EstT09.txt" __4},
	{E,0,"campaigns/terran/EstT10.txt","rez\\EstT10.txt" __4},
	{E,0,"campaigns/terran/EstT11.txt","rez\\EstT11.txt" __4},
	{E,0,"campaigns/terran/EstT12.txt","rez\\EstT12.txt" __4},

	// Zerg Campaigns
	{H,0,"campaigns/zerg/palza-blank","glue\\palza\\Blank.pcx",0 __3},
	{H,0,"campaigns/zerg/palza-tfont","glue\\palza\\tFont.pcx",0 __3},
	{H,0,"campaigns/zerg/palza-zerga","glue\\palza\\ZergA.pcx",0 __3},
	{H,0,"campaigns/zerg/palzb-blank","glue\\palzb\\Blank.pcx",0 __3},
	{H,0,"campaigns/zerg/palzb-tfont","glue\\palzb\\tFont.pcx",0 __3},
	{H,0,"campaigns/zerg/palzb-zergb","glue\\palzb\\ZergB.pcx",0 __3},
	{H,0,"campaigns/zerg/palzc-blank","glue\\palzc\\Blank.pcx",0 __3},
	{H,0,"campaigns/zerg/palzc-tfont","glue\\palzc\\tfont.pcx",0 __3},
	{H,0,"campaigns/zerg/palzc-zergc","glue\\palzc\\ZergC.pcx",0 __3},

	{L,0,"campaigns/zerg/tutorial/","campaign\\zerg\\tutorial\\staredit\\scenario.chk" __4},
	{L,0,"campaigns/zerg/01/","campaign\\zerg\\zerg01\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/01/ComBeep0","campaign\\zerg\\zerg01\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M01uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M01uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M02uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M02uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M03uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M03uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M04uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M04uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M05uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M05uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M06uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M06uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M07uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M07uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M08uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M08uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z0M09uda","campaign\\zerg\\zerg01\\staredit\\wav\\Z0M09uda.wav" __4},
	{W,0,"campaigns/zerg/01/Z1B00zad.wav","campaign\\zerg\\zerg01\\staredit\\wav\\Z1B00zad.wav" __4},
	{W,0,"campaigns/zerg/01/Z1B01zad.wav","campaign\\zerg\\zerg01\\staredit\\wav\\Z1B01zad.wav" __4},
	{W,0,"campaigns/zerg/01/Z1B02zad","campaign\\zerg\\zerg01\\staredit\\wav\\Z1B02zad.wav" __4},
	{W,0,"campaigns/zerg/01/Z1B03zad","campaign\\zerg\\zerg01\\staredit\\wav\\Z1B03zad.wav" __4},
	{W,0,"campaigns/zerg/01/Z1M00uza","campaign\\zerg\\zerg01\\staredit\\wav\\Z1M00uza.wav" __4},
	{W,0,"campaigns/zerg/01/zpwrdown","campaign\\zerg\\zerg01\\staredit\\wav\\zpwrdown.wav" __4},
	{L,0,"campaigns/zerg/02/","campaign\\zerg\\zerg02\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/02/ComBeep0","campaign\\zerg\\zerg02\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/02/Z2B00zad","campaign\\zerg\\zerg02\\staredit\\wav\\Z2B00zad.wav" __4},
	{W,0,"campaigns/zerg/02/Z2B01zad","campaign\\zerg\\zerg02\\staredit\\wav\\Z2B01zad.wav" __4},
	{W,0,"campaigns/zerg/02/Z2B02uza","campaign\\zerg\\zerg02\\staredit\\wav\\Z2B02uza.wav" __4},
	{W,0,"campaigns/zerg/02/Z2B03uda","campaign\\zerg\\zerg02\\staredit\\wav\\Z2B03uda.wav" __4},
	{W,0,"campaigns/zerg/02/Z2M00uda","campaign\\zerg\\zerg02\\staredit\\wav\\Z2M00uda.wav" __4},
	{W,0,"campaigns/zerg/02/Z2M20uza","campaign\\zerg\\zerg02\\staredit\\wav\\Z2M20uza.wav" __4},
	{W,0,"campaigns/zerg/02/Z2M21uda","campaign\\zerg\\zerg02\\staredit\\wav\\Z2M21uda.wav" __4},
	{L,0,"campaigns/zerg/03/","campaign\\zerg\\zerg03\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/03/ComBeep0","campaign\\zerg\\zerg03\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/03/Z3B00zad","campaign\\zerg\\zerg03\\staredit\\wav\\Z3B00zad.wav" __4},
	{W,0,"campaigns/zerg/03/Z3B01uza","campaign\\zerg\\zerg03\\staredit\\wav\\Z3B01uza.wav" __4},
	{W,0,"campaigns/zerg/03/Z3B02udu","campaign\\zerg\\zerg03\\staredit\\wav\\Z3B02udu.wav" __4},
	{W,0,"campaigns/zerg/03/Z3B03uda","campaign\\zerg\\zerg03\\staredit\\wav\\Z3B03uda.wav" __4},
	{W,0,"campaigns/zerg/03/Z3M00udu","campaign\\zerg\\zerg03\\staredit\\wav\\Z3M00udu.wav" __4},
	{W,0,"campaigns/zerg/03/Z3M01uda","campaign\\zerg\\zerg03\\staredit\\wav\\Z3M01uda.wav" __4},
	{W,0,"campaigns/zerg/03/Z3M02uza","campaign\\zerg\\zerg03\\staredit\\wav\\Z3M02uza.wav" __4},
	{W,0,"campaigns/zerg/03/zpwrdown","campaign\\zerg\\zerg03\\staredit\\wav\\zpwrdown.wav" __4},
	{L,0,"campaigns/zerg/04/","campaign\\zerg\\zerg04\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/04/ComBeep0","campaign\\zerg\\zerg04\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/04/Z4B00uza","campaign\\zerg\\zerg04\\staredit\\wav\\Z4B00uza.wav" __4},
	{W,0,"campaigns/zerg/04/Z4B01zad","campaign\\zerg\\zerg04\\staredit\\wav\\Z4B01zad.wav" __4},
	{W,0,"campaigns/zerg/04/Z4B02zad","campaign\\zerg\\zerg04\\staredit\\wav\\Z4B02zad.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M00ura","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M00ura.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M20uza","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M20uza.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M40zad","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M40zad.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M41uki","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M41uki.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M42zad","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M42zad.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M43ura","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M43ura.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M60ura","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M60ura.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M61uki","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M61uki.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M62ura","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M62ura.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M63uki","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M63uki.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M65ura","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M65ura.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M66uki","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M66uki.wav" __4},
	{W,0,"campaigns/zerg/04/Z4M67ura","campaign\\zerg\\zerg04\\staredit\\wav\\Z4M67ura.wav" __4},
	{L,0,"campaigns/zerg/05/","campaign\\zerg\\zerg05\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/05/ComBeep0","campaign\\zerg\\zerg05\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/05/ComBeep1","campaign\\zerg\\zerg05\\staredit\\wav\\ComBeep1.wav" __4},
	{W,0,"campaigns/zerg/05/P6M00tad","campaign\\zerg\\zerg05\\staredit\\wav\\P6M00tad.wav" __4},
	{W,0,"campaigns/zerg/05/PPwrDown","campaign\\zerg\\zerg05\\staredit\\wav\\PPwrDown.wav" __4},
	{W,0,"campaigns/zerg/05/T4M70tad","campaign\\zerg\\zerg05\\staredit\\wav\\T4M70tad.wav" __4},
	{W,0,"campaigns/zerg/05/TBM21uma","campaign\\zerg\\zerg05\\staredit\\wav\\TBM21uma.wav" __4},
	{W,0,"campaigns/zerg/05/Z5B00uki","campaign\\zerg\\zerg05\\staredit\\wav\\Z5B00uki.wav" __4},
	{W,0,"campaigns/zerg/05/Z5B01uki","campaign\\zerg\\zerg05\\staredit\\wav\\Z5B01uki.wav" __4},
	{W,0,"campaigns/zerg/05/Z5B02uza","campaign\\zerg\\zerg05\\staredit\\wav\\Z5B02uza.wav" __4},
	{W,0,"campaigns/zerg/05/Z5B03uki","campaign\\zerg\\zerg05\\staredit\\wav\\Z5B03uki.wav" __4},
	{W,0,"campaigns/zerg/05/Z5B04zad","campaign\\zerg\\zerg05\\staredit\\wav\\Z5B04zad.wav" __4},
	{W,0,"campaigns/zerg/05/Z5B05uza","campaign\\zerg\\zerg05\\staredit\\wav\\Z5B05uza.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M00tad","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M00tad.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M00uda","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M00uda.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M20uci","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M20uci.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M20uki","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M20uki.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M30uci","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M30uci.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M40uma","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M40uma.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M50uma","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M50uma.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M51uma","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M51uma.wav" __4},
	{W,0,"campaigns/zerg/05/Z5M60uda","campaign\\zerg\\zerg05\\staredit\\wav\\Z5M60uda.wav" __4},
	{W,0,"campaigns/zerg/05/zpwrdown","campaign\\zerg\\zerg05\\staredit\\wav\\zpwrdown.wav" __4},
	{L,0,"campaigns/zerg/06/","campaign\\zerg\\zerg06\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/06/ComBeep0","campaign\\zerg\\zerg06\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/06/ComBeep1","campaign\\zerg\\zerg06\\staredit\\wav\\ComBeep1.wav" __4},
	{W,0,"campaigns/zerg/06/Z6B00uki","campaign\\zerg\\zerg06\\staredit\\wav\\Z6B00uki.wav" __4},
	{W,0,"campaigns/zerg/06/Z6B01uki","campaign\\zerg\\zerg06\\staredit\\wav\\Z6B01uki.wav" __4},
	{W,0,"campaigns/zerg/06/Z6B02uta","campaign\\zerg\\zerg06\\staredit\\wav\\Z6B02uta.wav" __4},
	{W,0,"campaigns/zerg/06/Z6B03uki","campaign\\zerg\\zerg06\\staredit\\wav\\Z6B03uki.wav" __4},
	{W,0,"campaigns/zerg/06/Z6B04uta","campaign\\zerg\\zerg06\\staredit\\wav\\Z6B04uta.wav" __4},
	{W,0,"campaigns/zerg/06/Z6B05uki","campaign\\zerg\\zerg06\\staredit\\wav\\Z6B05uki.wav" __4},
	{W,0,"campaigns/zerg/06/Z6M00uza","campaign\\zerg\\zerg06\\staredit\\wav\\Z6M00uza.wav" __4},
	{W,0,"campaigns/zerg/06/Z6M01uki","campaign\\zerg\\zerg06\\staredit\\wav\\Z6M01uki.wav" __4},
	{W,0,"campaigns/zerg/06/Z6M02uza","campaign\\zerg\\zerg06\\staredit\\wav\\Z6M02uza.wav" __4},
	{W,0,"campaigns/zerg/06/Z6M20uki","campaign\\zerg\\zerg06\\staredit\\wav\\Z6M20uki.wav" __4},
	{W,0,"campaigns/zerg/06/Z6M40uta","campaign\\zerg\\zerg06\\staredit\\wav\\Z6M40uta.wav" __4},
	{W,0,"campaigns/zerg/06/Z6M60uki","campaign\\zerg\\zerg06\\staredit\\wav\\Z6M60uki.wav" __4},
	{W,0,"campaigns/zerg/06/Z6M61uta","campaign\\zerg\\zerg06\\staredit\\wav\\Z6M61uta.wav" __4},
	{L,0,"campaigns/zerg/07/","campaign\\zerg\\zerg07\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/07/Z7B00uki","campaign\\zerg\\zerg07\\staredit\\wav\\Z7B00uki.wav" __4},
	{W,0,"campaigns/zerg/07/Z7B01uda","campaign\\zerg\\zerg07\\staredit\\wav\\Z7B01uda.wav" __4},
	{W,0,"campaigns/zerg/07/Z7B02uki","campaign\\zerg\\zerg07\\staredit\\wav\\Z7B02uki.wav" __4},
	{W,0,"campaigns/zerg/07/Z7B03uda","campaign\\zerg\\zerg07\\staredit\\wav\\Z7B03uda.wav" __4},
	{W,0,"campaigns/zerg/07/Z7B04uki","campaign\\zerg\\zerg07\\staredit\\wav\\Z7B04uki.wav" __4},
	{W,0,"campaigns/zerg/07/Z7B05uda","campaign\\zerg\\zerg07\\staredit\\wav\\Z7B05uda.wav" __4},
	{L,0,"campaigns/zerg/08/","campaign\\zerg\\zerg08\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/08/ComBeep0","campaign\\zerg\\zerg08\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/08/Z8B00zad","campaign\\zerg\\zerg08\\staredit\\wav\\Z8B00zad.wav" __4},
	{W,0,"campaigns/zerg/08/Z8B01zad","campaign\\zerg\\zerg08\\staredit\\wav\\Z8B01zad.wav" __4},
	{W,0,"campaigns/zerg/08/Z8B02zad","campaign\\zerg\\zerg08\\staredit\\wav\\Z8B02zad.wav" __4},
	{W,0,"campaigns/zerg/08/Z8B03uda","campaign\\zerg\\zerg08\\staredit\\wav\\Z8B03uda.wav" __4},
	{W,0,"campaigns/zerg/08/Z8M00uda","campaign\\zerg\\zerg08\\staredit\\wav\\Z8M00uda.wav" __4},
	{W,0,"campaigns/zerg/08/Z8M20uda","campaign\\zerg\\zerg08\\staredit\\wav\\Z8M20uda.wav" __4},
	{W,0,"campaigns/zerg/08/Z8M40uki","campaign\\zerg\\zerg08\\staredit\\wav\\Z8M40uki.wav" __4},
	{W,0,"campaigns/zerg/08/Z8M41uze","campaign\\zerg\\zerg08\\staredit\\wav\\Z8M41uze.wav" __4},
	{W,0,"campaigns/zerg/08/Z8M42uki","campaign\\zerg\\zerg08\\staredit\\wav\\Z8M42uki.wav" __4},
	{W,0,"campaigns/zerg/08/Z8M60uki","campaign\\zerg\\zerg08\\staredit\\wav\\Z8M60uki.wav" __4},
	// "campaigns/zerg/09/scenario.chk" => crash in importer with CompaignConverter!
	//{L,0,"campaigns/zerg/09/","campaign\\zerg\\zerg09\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/09/ComBeep0","campaign\\zerg\\zerg09\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/09/Z9B00zad","campaign\\zerg\\zerg09\\staredit\\wav\\Z9B00zad.wav" __4},
	{W,0,"campaigns/zerg/09/Z9B01zad","campaign\\zerg\\zerg09\\staredit\\wav\\Z9B01zad.wav" __4},
	{W,0,"campaigns/zerg/09/Z9B02zad","campaign\\zerg\\zerg09\\staredit\\wav\\Z9B02zad.wav" __4},
	{W,0,"campaigns/zerg/09/Z9M00uda","campaign\\zerg\\zerg09\\staredit\\wav\\Z9M00uda.wav" __4},
	{W,0,"campaigns/zerg/09/Z9M01uda","campaign\\zerg\\zerg09\\staredit\\wav\\Z9M01uda.wav" __4},
	{W,0,"campaigns/zerg/09/zdrErr00","campaign\\zerg\\zerg09\\staredit\\wav\\zdrErr00.wav" __4},
	{W,0,"campaigns/zerg/09/ZDrMin00","campaign\\zerg\\zerg09\\staredit\\wav\\ZDrMin00.wav" __4},
	{L,0,"campaigns/zerg/10/","campaign\\zerg\\zerg10\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/zerg/10/ComBeep0","campaign\\zerg\\zerg10\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/zerg/10/ZAB00zad","campaign\\zerg\\zerg10\\staredit\\wav\\ZAB00zad.wav" __4},
	{W,0,"campaigns/zerg/10/ZAB01zad","campaign\\zerg\\zerg10\\staredit\\wav\\ZAB01zad.wav" __4},
	{W,0,"campaigns/zerg/10/ZAB02zad","campaign\\zerg\\zerg10\\staredit\\wav\\ZAB02zad.wav" __4},
	{W,0,"campaigns/zerg/10/ZAM00uda","campaign\\zerg\\zerg10\\staredit\\wav\\ZAM00uda.wav" __4},
	{W,0,"campaigns/zerg/10/ZAM20zad","campaign\\zerg\\zerg10\\staredit\\wav\\ZAM20zad.wav" __4},

	{E,0,"campaigns/zerg/EstZ0t.txt","rez\\EstZ0t.txt" __4},
	{E,0,"campaigns/zerg/EstZ01.txt","rez\\EstZ01.txt" __4},
	{E,0,"campaigns/zerg/EstZ02.txt","rez\\EstZ02.txt" __4},
	{E,0,"campaigns/zerg/EstZ03.txt","rez\\EstZ03.txt" __4},
	{E,0,"campaigns/zerg/EstZ04.txt","rez\\EstZ04.txt" __4},
	{E,0,"campaigns/zerg/EstZ05.txt","rez\\EstZ05.txt" __4},
	{E,0,"campaigns/zerg/EstZ06.txt","rez\\EstZ06.txt" __4},
	{E,0,"campaigns/zerg/EstZ07.txt","rez\\EstZ07.txt" __4},
	{E,0,"campaigns/zerg/EstZ08.txt","rez\\EstZ08.txt" __4},
	{E,0,"campaigns/zerg/EstZ09.txt","rez\\EstZ09.txt" __4},
	{E,0,"campaigns/zerg/EstZ10.txt","rez\\EstZ10.txt" __4},

	// Protoss Campaigns
	{H,0,"campaigns/protoss/palpa-blank",   "glue\\palpa\\Blank.pcx",0 __3},
	{H,0,"campaigns/protoss/palpa-tfont",   "glue\\palpa\\tFont.pcx",0 __3},
	{H,0,"campaigns/protoss/palpa-protossa","glue\\palpa\\protossa.pcx",0 __3},
	{H,0,"campaigns/protoss/palpb-blank",   "glue\\palpb\\Blank.pcx",0 __3},
	{H,0,"campaigns/protoss/palpb-tfont",   "glue\\palpb\\tFont.pcx",0 __3},
	{H,0,"campaigns/protoss/palpb-protossb","glue\\palpb\\protossb.pcx",0 __3},
	{H,0,"campaigns/protoss/palpc-blank",   "glue\\palpc\\Blank.pcx",0 __3},
	{H,0,"campaigns/protoss/palpc-tfont",   "glue\\palpc\\tfont.pcx",0 __3},
	{H,0,"campaigns/protoss/palpc-protossc","glue\\palpc\\protossc.pcx",0 __3},

	{L,0,"campaigns/protoss/tutorial/","campaign\\protoss\\tutorial\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/tutorial/P1B00pad","campaign\\protoss\\tutorial\\staredit\\wav\\P1B00pad.wav" __4},
	{W,0,"campaigns/protoss/tutorial/P1B01pad","campaign\\protoss\\tutorial\\staredit\\wav\\P1B01pad.wav" __4},
	{W,0,"campaigns/protoss/tutorial/P1B02pad","campaign\\protoss\\tutorial\\staredit\\wav\\P1B02pad.wav" __4},
	{W,0,"campaigns/protoss/tutorial/P1M00ufe","campaign\\protoss\\tutorial\\staredit\\wav\\P1M00ufe.wav" __4},
	{W,0,"campaigns/protoss/tutorial/P1M20ufe","campaign\\protoss\\tutorial\\staredit\\wav\\P1M20ufe.wav" __4},
	{W,0,"campaigns/protoss/tutorial/P1M40ufe","campaign\\protoss\\tutorial\\staredit\\wav\\P1M40ufe.wav" __4},
	{L,0,"campaigns/protoss/01/","campaign\\protoss\\protoss01\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/01/ComBeep0","campaign\\protoss\\protoss01\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/01/P1B00pad","campaign\\protoss\\protoss01\\staredit\\wav\\P1B00pad.wav" __4},
	{W,0,"campaigns/protoss/01/P1B01pad","campaign\\protoss\\protoss01\\staredit\\wav\\P1B01pad.wav" __4},
	{W,0,"campaigns/protoss/01/P1B02pad","campaign\\protoss\\protoss01\\staredit\\wav\\P1B02pad.wav" __4},
	{W,0,"campaigns/protoss/01/P1M00ufe","campaign\\protoss\\protoss01\\staredit\\wav\\P1M00ufe.wav" __4},
	{W,0,"campaigns/protoss/01/P1M40ufe","campaign\\protoss\\protoss01\\staredit\\wav\\P1M40ufe.wav" __4},
	{W,0,"campaigns/protoss/01/P1M60ufe","campaign\\protoss\\protoss01\\staredit\\wav\\P1M60ufe.wav" __4},
	{W,0,"campaigns/protoss/01/P1M61ufe","campaign\\protoss\\protoss01\\staredit\\wav\\P1M61ufe.wav" __4},
	{W,0,"campaigns/protoss/01/P1M62ufe","campaign\\protoss\\protoss01\\staredit\\wav\\P1M62ufe.wav" __4},
	{L,0,"campaigns/protoss/02/","campaign\\protoss\\protoss02\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/02/ComBeep0","campaign\\protoss\\protoss02\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/02/P2B00pad","campaign\\protoss\\protoss02\\staredit\\wav\\P2B00pad.wav" __4},
	{W,0,"campaigns/protoss/02/P2B01uta","campaign\\protoss\\protoss02\\staredit\\wav\\P2B01uta.wav" __4},
	{W,0,"campaigns/protoss/02/P2B02pad","campaign\\protoss\\protoss02\\staredit\\wav\\P2B02pad.wav" __4},
	{W,0,"campaigns/protoss/02/P2B03uta","campaign\\protoss\\protoss02\\staredit\\wav\\P2B03uta.wav" __4},
	{W,0,"campaigns/protoss/02/P2B04uta","campaign\\protoss\\protoss02\\staredit\\wav\\P2B04uta.wav" __4},
	{W,0,"campaigns/protoss/02/P2B06pad","campaign\\protoss\\protoss02\\staredit\\wav\\P2B06pad.wav" __4},
	{W,0,"campaigns/protoss/02/P2B07uta","campaign\\protoss\\protoss02\\staredit\\wav\\P2B07uta.wav" __4},
	{W,0,"campaigns/protoss/02/P2B08uta","campaign\\protoss\\protoss02\\staredit\\wav\\P2B08uta.wav" __4},
	{W,0,"campaigns/protoss/02/P2B09pad","campaign\\protoss\\protoss02\\staredit\\wav\\P2B09pad.wav" __4},
	{W,0,"campaigns/protoss/02/P2B10uta","campaign\\protoss\\protoss02\\staredit\\wav\\P2B10uta.wav" __4},
	{W,0,"campaigns/protoss/02/P2B11ufe","campaign\\protoss\\protoss02\\staredit\\wav\\P2B11ufe.wav" __4},
	{W,0,"campaigns/protoss/02/P2M00ufe","campaign\\protoss\\protoss02\\staredit\\wav\\P2M00ufe.wav" __4},
	{W,0,"campaigns/protoss/02/P2M01ufe","campaign\\protoss\\protoss02\\staredit\\wav\\P2M01ufe.wav" __4},
	{L,0,"campaigns/protoss/03/","campaign\\protoss\\protoss03\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/03/P3B00ufe","campaign\\protoss\\protoss03\\staredit\\wav\\P3B00ufe.wav" __4},
	{W,0,"campaigns/protoss/03/P3B01pad","campaign\\protoss\\protoss03\\staredit\\wav\\P3B01pad.wav" __4},
	{W,0,"campaigns/protoss/03/P3B02pad","campaign\\protoss\\protoss03\\staredit\\wav\\P3B02pad.wav" __4},
	{W,0,"campaigns/protoss/03/P3B03ufe","campaign\\protoss\\protoss03\\staredit\\wav\\P3B03ufe.wav" __4},
	{W,0,"campaigns/protoss/03/P3M00ufe","campaign\\protoss\\protoss03\\staredit\\wav\\P3M00ufe.wav" __4},
	{W,0,"campaigns/protoss/03/P3M01pad","campaign\\protoss\\protoss03\\staredit\\wav\\P3M01pad.wav" __4},
	{L,0,"campaigns/protoss/04/","campaign\\protoss\\protoss04\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/04/ComBeep0","campaign\\protoss\\protoss04\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/04/P4B00pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4B00pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4B01pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4B01pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4B02pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4B02pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4B03pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4B03pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4M00uta","campaign\\protoss\\protoss04\\staredit\\wav\\P4M00uta.wav" __4},
	{W,0,"campaigns/protoss/04/P4M01pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4M01pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4M02uta","campaign\\protoss\\protoss04\\staredit\\wav\\P4M02uta.wav" __4},
	{W,0,"campaigns/protoss/04/P4M03ura","campaign\\protoss\\protoss04\\staredit\\wav\\P4M03ura.wav" __4},
	{W,0,"campaigns/protoss/04/P4M04pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4M04pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4M05ura","campaign\\protoss\\protoss04\\staredit\\wav\\P4M05ura.wav" __4},
	{W,0,"campaigns/protoss/04/P4M06pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4M06pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4M07uta","campaign\\protoss\\protoss04\\staredit\\wav\\P4M07uta.wav" __4},
	{W,0,"campaigns/protoss/04/P4M09pad","campaign\\protoss\\protoss04\\staredit\\wav\\P4M09pad.wav" __4},
	{W,0,"campaigns/protoss/04/P4M10uta","campaign\\protoss\\protoss04\\staredit\\wav\\P4M10uta.wav" __4},
	{W,0,"campaigns/protoss/04/P4M11ute","campaign\\protoss\\protoss04\\staredit\\wav\\P4M11ute.wav" __4},
	{W,0,"campaigns/protoss/04/P4M20uta","campaign\\protoss\\protoss04\\staredit\\wav\\P4M20uta.wav" __4},
	{W,0,"campaigns/protoss/04/zhyRdy00","campaign\\protoss\\protoss04\\staredit\\wav\\zhyRdy00.wav" __4},
	{W,0,"campaigns/protoss/04/zhyYes03","campaign\\protoss\\protoss04\\staredit\\wav\\zhyYes03.wav" __4},
	{W,0,"campaigns/protoss/04/zquRdy00","campaign\\protoss\\protoss04\\staredit\\wav\\zquRdy00.wav" __4},
	{W,0,"campaigns/protoss/04/ZZeRdy00","campaign\\protoss\\protoss04\\staredit\\wav\\ZZeRdy00.wav" __4},
	{L,0,"campaigns/protoss/05/","campaign\\protoss\\protoss05\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/05/ComBeep0","campaign\\protoss\\protoss05\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/05/P5B00pad","campaign\\protoss\\protoss05\\staredit\\wav\\P5B00pad.wav" __4},
	{W,0,"campaigns/protoss/05/P5B01uta","campaign\\protoss\\protoss05\\staredit\\wav\\P5B01uta.wav" __4},
	{W,0,"campaigns/protoss/05/P5B02pad","campaign\\protoss\\protoss05\\staredit\\wav\\P5B02pad.wav" __4},
	{W,0,"campaigns/protoss/05/P5B03uta","campaign\\protoss\\protoss05\\staredit\\wav\\P5B03uta.wav" __4},
	{W,0,"campaigns/protoss/05/P5B04uta","campaign\\protoss\\protoss05\\staredit\\wav\\P5B04uta.wav" __4},
	{W,0,"campaigns/protoss/05/P5B05pad","campaign\\protoss\\protoss05\\staredit\\wav\\P5B05pad.wav" __4},
	{W,0,"campaigns/protoss/05/P5B06uta","campaign\\protoss\\protoss05\\staredit\\wav\\P5B06uta.wav" __4},
	{W,0,"campaigns/protoss/05/P5B07uta","campaign\\protoss\\protoss05\\staredit\\wav\\P5B07uta.wav" __4},
	{W,0,"campaigns/protoss/05/P5B08pad","campaign\\protoss\\protoss05\\staredit\\wav\\P5B08pad.wav" __4},
	{W,0,"campaigns/protoss/05/P5M00udu","campaign\\protoss\\protoss05\\staredit\\wav\\P5M00udu.wav" __4},
	{W,0,"campaigns/protoss/05/P5M03uta","campaign\\protoss\\protoss05\\staredit\\wav\\P5M03uta.wav" __4},
	{W,0,"campaigns/protoss/05/P5M04udu","campaign\\protoss\\protoss05\\staredit\\wav\\P5M04udu.wav" __4},
	{L,0,"campaigns/protoss/06/","campaign\\protoss\\protoss06\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/06/ComBeep0","campaign\\protoss\\protoss06\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/06/P6B00uta","campaign\\protoss\\protoss06\\staredit\\wav\\P6B00uta.wav" __4},
	{W,0,"campaigns/protoss/06/P6B01ura","campaign\\protoss\\protoss06\\staredit\\wav\\P6B01ura.wav" __4},
	{W,0,"campaigns/protoss/06/P6B02uta","campaign\\protoss\\protoss06\\staredit\\wav\\P6B02uta.wav" __4},
	{W,0,"campaigns/protoss/06/P6M00tad","campaign\\protoss\\protoss06\\staredit\\wav\\P6M00tad.wav" __4},
	{W,0,"campaigns/protoss/06/P6M00uta","campaign\\protoss\\protoss06\\staredit\\wav\\P6M00uta.wav" __4},
	{W,0,"campaigns/protoss/06/P6M01uze","campaign\\protoss\\protoss06\\staredit\\wav\\P6M01uze.wav" __4},
	{W,0,"campaigns/protoss/06/P6M03uta","campaign\\protoss\\protoss06\\staredit\\wav\\P6M03uta.wav" __4},
	{W,0,"campaigns/protoss/06/P6M04uze","campaign\\protoss\\protoss06\\staredit\\wav\\P6M04uze.wav" __4},
	{W,0,"campaigns/protoss/06/P6M20uma","campaign\\protoss\\protoss06\\staredit\\wav\\P6M20uma.wav" __4},
	{W,0,"campaigns/protoss/06/P6M30uma","campaign\\protoss\\protoss06\\staredit\\wav\\P6M30uma.wav" __4},
	{W,0,"campaigns/protoss/06/P6M40uma","campaign\\protoss\\protoss06\\staredit\\wav\\P6M40uma.wav" __4},
	{W,0,"campaigns/protoss/06/pshBld03","campaign\\protoss\\protoss06\\staredit\\wav\\pshBld03.wav" __4},
	{W,0,"campaigns/protoss/06/TMaPss00","campaign\\protoss\\protoss06\\staredit\\wav\\TMaPss00.wav" __4},
	{W,0,"campaigns/protoss/06/ZBgRdy00","campaign\\protoss\\protoss06\\staredit\\wav\\ZBgRdy00.wav" __4},
	{W,0,"campaigns/protoss/06/ZZeRdy00","campaign\\protoss\\protoss06\\staredit\\wav\\ZZeRdy00.wav" __4},
	{W,0,"campaigns/protoss/06/ZZeYes01","campaign\\protoss\\protoss06\\staredit\\wav\\ZZeYes01.wav" __4},
	{W,0,"campaigns/protoss/06/ZZeYes03","campaign\\protoss\\protoss06\\staredit\\wav\\ZZeYes03.wav" __4},
	{L,0,"campaigns/protoss/07/","campaign\\protoss\\protoss07\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/07/ComBeep0","campaign\\protoss\\protoss07\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/07/P7B00ufd","campaign\\protoss\\protoss07\\staredit\\wav\\P7B00ufd.wav" __4},
	{W,0,"campaigns/protoss/07/P7B01uta","campaign\\protoss\\protoss07\\staredit\\wav\\P7B01uta.wav" __4},
	{W,0,"campaigns/protoss/07/P7B02ufd","campaign\\protoss\\protoss07\\staredit\\wav\\P7B02ufd.wav" __4},
	{W,0,"campaigns/protoss/07/P7B03uta","campaign\\protoss\\protoss07\\staredit\\wav\\P7B03uta.wav" __4},
	{W,0,"campaigns/protoss/07/P7B04ufd","campaign\\protoss\\protoss07\\staredit\\wav\\P7B04ufd.wav" __4},
	{W,0,"campaigns/protoss/07/P7B05ufd","campaign\\protoss\\protoss07\\staredit\\wav\\P7B05ufd.wav" __4},
	{W,0,"campaigns/protoss/07/P7B06uta","campaign\\protoss\\protoss07\\staredit\\wav\\P7B06uta.wav" __4},
	{W,0,"campaigns/protoss/07/P7B07ufd","campaign\\protoss\\protoss07\\staredit\\wav\\P7B07ufd.wav" __4},
	{W,0,"campaigns/protoss/07/P7B08uta","campaign\\protoss\\protoss07\\staredit\\wav\\P7B08uta.wav" __4},
	{W,0,"campaigns/protoss/07/P7M00pad","campaign\\protoss\\protoss07\\staredit\\wav\\P7M00pad.wav" __4},
	{W,0,"campaigns/protoss/07/P7M01uta","campaign\\protoss\\protoss07\\staredit\\wav\\P7M01uta.wav" __4},
	{W,0,"campaigns/protoss/07/P7M20uta","campaign\\protoss\\protoss07\\staredit\\wav\\P7M20uta.wav" __4},
	{W,0,"campaigns/protoss/07/P7M21pad","campaign\\protoss\\protoss07\\staredit\\wav\\P7M21pad.wav" __4},
	{W,0,"campaigns/protoss/07/P7M23uta","campaign\\protoss\\protoss07\\staredit\\wav\\P7M23uta.wav" __4},
	{W,0,"campaigns/protoss/07/pshBld03","campaign\\protoss\\protoss07\\staredit\\wav\\pshBld03.wav" __4},
	{L,0,"campaigns/protoss/08/","campaign\\protoss\\protoss08\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/08/ComBeep0","campaign\\protoss\\protoss08\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/08/ComBeep1","campaign\\protoss\\protoss08\\staredit\\wav\\ComBeep1.wav" __4},
	{W,0,"campaigns/protoss/08/P8B00ufd","campaign\\protoss\\protoss08\\staredit\\wav\\P8B00ufd.wav" __4},
	{W,0,"campaigns/protoss/08/P8B01ufd","campaign\\protoss\\protoss08\\staredit\\wav\\P8B01ufd.wav" __4},
	{W,0,"campaigns/protoss/08/P8B02ura","campaign\\protoss\\protoss08\\staredit\\wav\\P8B02ura.wav" __4},
	{W,0,"campaigns/protoss/08/P8B03ufd","campaign\\protoss\\protoss08\\staredit\\wav\\P8B03ufd.wav" __4},
	{W,0,"campaigns/protoss/08/P8M00ufd","campaign\\protoss\\protoss08\\staredit\\wav\\P8M00ufd.wav" __4},
	{W,0,"campaigns/protoss/08/P8M01pad","campaign\\protoss\\protoss08\\staredit\\wav\\P8M01pad.wav" __4},
	{W,0,"campaigns/protoss/08/P8M02uze","campaign\\protoss\\protoss08\\staredit\\wav\\P8M02uze.wav" __4},
	{W,0,"campaigns/protoss/08/P8M03pad","campaign\\protoss\\protoss08\\staredit\\wav\\P8M03pad.wav" __4},
	{W,0,"campaigns/protoss/08/P8M04uze","campaign\\protoss\\protoss08\\staredit\\wav\\P8M04uze.wav" __4},
	{W,0,"campaigns/protoss/08/P8M05pad","campaign\\protoss\\protoss08\\staredit\\wav\\P8M05pad.wav" __4},
	{W,0,"campaigns/protoss/08/P8M06uze","campaign\\protoss\\protoss08\\staredit\\wav\\P8M06uze.wav" __4},
	{W,0,"campaigns/protoss/08/P8M08pad","campaign\\protoss\\protoss08\\staredit\\wav\\P8M08pad.wav" __4},
	{W,0,"campaigns/protoss/08/pshBld03","campaign\\protoss\\protoss08\\staredit\\wav\\pshBld03.wav" __4},
	{L,0,"campaigns/protoss/09/","campaign\\protoss\\protoss09\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/09/ComBeep0","campaign\\protoss\\protoss09\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/09/P9B00uta","campaign\\protoss\\protoss09\\staredit\\wav\\P9B00uta.wav" __4},
	{W,0,"campaigns/protoss/09/P9B01uze","campaign\\protoss\\protoss09\\staredit\\wav\\P9B01uze.wav" __4},
	{W,0,"campaigns/protoss/09/P9B02uze","campaign\\protoss\\protoss09\\staredit\\wav\\P9B02uze.wav" __4},
	{W,0,"campaigns/protoss/09/P9B03uta","campaign\\protoss\\protoss09\\staredit\\wav\\P9B03uta.wav" __4},
	{W,0,"campaigns/protoss/09/P9B04ufd","campaign\\protoss\\protoss09\\staredit\\wav\\P9B04ufd.wav" __4},
	{L,0,"campaigns/protoss/10/","campaign\\protoss\\protoss10\\staredit\\scenario.chk" __4},
	{W,0,"campaigns/protoss/10/ComBeep0","campaign\\protoss\\protoss10\\staredit\\wav\\ComBeep0.wav" __4},
	{W,0,"campaigns/protoss/10/P9M00pad","campaign\\protoss\\protoss10\\staredit\\wav\\P9M00pad.wav" __4},
	{W,0,"campaigns/protoss/10/P9M02ura","campaign\\protoss\\protoss10\\staredit\\wav\\P9M02ura.wav" __4},
	{W,0,"campaigns/protoss/10/PAB00ufd","campaign\\protoss\\protoss10\\staredit\\wav\\PAB00ufd.wav" __4},
	{W,0,"campaigns/protoss/10/PAB01uta","campaign\\protoss\\protoss10\\staredit\\wav\\PAB01uta.wav" __4},
	{W,0,"campaigns/protoss/10/PAB02uta","campaign\\protoss\\protoss10\\staredit\\wav\\PAB02uta.wav" __4},
	{W,0,"campaigns/protoss/10/PAB03uze","campaign\\protoss\\protoss10\\staredit\\wav\\PAB03uze.wav" __4},
	{W,0,"campaigns/protoss/10/PAB05ura","campaign\\protoss\\protoss10\\staredit\\wav\\PAB05ura.wav" __4},
	{W,0,"campaigns/protoss/10/PAB06uta","campaign\\protoss\\protoss10\\staredit\\wav\\PAB06uta.wav" __4},
	{W,0,"campaigns/protoss/10/PAM00uta","campaign\\protoss\\protoss10\\staredit\\wav\\PAM00uta.wav" __4},

	{E,0,"campaigns/protoss/EstP0t.txt","rez\\EstP0t.txt" __4},
	{E,0,"campaigns/protoss/EstP01.txt","rez\\EstP01.txt" __4},
	{E,0,"campaigns/protoss/EstP02.txt","rez\\EstP02.txt" __4},
	{E,0,"campaigns/protoss/EstP03.txt","rez\\EstP03.txt" __4},
	{E,0,"campaigns/protoss/EstP04.txt","rez\\EstP04.txt" __4},
	{E,0,"campaigns/protoss/EstP05.txt","rez\\EstP05.txt" __4},
	{E,0,"campaigns/protoss/EstP06.txt","rez\\EstP06.txt" __4},
	{E,0,"campaigns/protoss/EstP07.txt","rez\\EstP07.txt" __4},
	{E,0,"campaigns/protoss/EstP08.txt","rez\\EstP08.txt" __4},
	{E,0,"campaigns/protoss/EstP09.txt","rez\\EstP09.txt" __4},
	{E,0,"campaigns/protoss/EstP10.txt","rez\\EstP10.txt" __4},

	// Music
	{W,0,"music/title","music\\title.wav" __4},
	{W,0,"music/terran/defeat","music\\tdefeat.wav" __4},
	{W,0,"music/terran/1","music\\terran1.wav" __4},
	{W,0,"music/terran/2","music\\terran2.wav" __4},
	{W,0,"music/terran/3","music\\terran3.wav" __4},
	{W,0,"music/terran/ready room","music\\trdyroom.wav" __4},
	{W,0,"music/terran/victory","music\\tvict.wav" __4},
	{W,0,"music/zerg/defeat","music\\zdefeat.wav" __4},
	{W,0,"music/zerg/1","music\\zerg1.wav" __4},
	{W,0,"music/zerg/2","music\\zerg2.wav" __4},
	{W,0,"music/zerg/3","music\\zerg3.wav" __4},
	{W,0,"music/zerg/ready room","music\\zrdyroom.wav" __4},
	{W,0,"music/zerg/victory","music\\zvict.wav" __4},
	{W,0,"music/protoss/defeat","music\\pdefeat.wav" __4},
	{W,0,"music/protoss/1","music\\protoss1.wav" __4},
	{W,0,"music/protoss/2","music\\protoss2.wav" __4},
	{W,0,"music/protoss/3","music\\protoss3.wav" __4},
	{W,0,"music/protoss/ready room","music\\prdyroom.wav" __4},
	{W,0,"music/protoss/victory","music\\pvict.wav" __4},

	//Video
	{V,0,"preprotoss_2","smk\\preprotoss_2.smk" __4},
	{V,0,"prezerg_3","smk\\prezerg_3.smk" __4},
	{V,0,"preterran_4","smk\\preterran_4.smk" __4},
	{V,0,"protoss1","smk\\protoss1.smk" __4},
	{V,0,"terran1","smk\\terran1.smk" __4},
	{V,0,"terran3","smk\\terran3.smk" __4},
	{V,0,"protoss2","smk\\protoss2.smk" __4},
	{V,0,"starintr","smk\\starintr.smk" __4},
	{V,0,"preprotoss_1","smk\\preprotoss_1.smk" __4},
	{V,0,"preprotoss_3","smk\\preprotoss_3.smk" __4},
	{V,0,"prezerg_4","smk\\prezerg_4.smk" __4},
	{V,0,"preterran_3","smk\\preterran_3.smk" __4},
	{V,0,"blizzard","smk\\blizzard.smk" __4},
	{V,0,"preterran_1","smk\\preterran_1.smk" __4},
	{V,0,"terran4","smk\\terran4.smk" __4},
	{V,0,"protoss3","smk\\protoss3.smk" __4},
	{V,0,"protoss4","smk\\protoss4.smk" __4},
	{V,0,"prezerg_2","smk\\prezerg_2.smk" __4},
	{V,0,"preterran_2","smk\\preterran_2.smk" __4},
	{V,0,"terran2","smk\\terran2.smk" __4},
	{V,0,"zerg2","smk\\zerg2.smk" __4},
	{V,0,"zerg3","smk\\zerg3.smk" __4},
	{V,0,"zerg4","smk\\zerg4.smk" __4},
	{V,0,"zerg1","smk\\zerg1.smk" __4},


};

#endif /* STARTOOL_CD_H_ */
