name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu_build:
    name: Ubuntu build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run:  |
        sudo apt-get install -yy libpng-dev libgtk2.0-dev zlib1g-dev libstorm-dev libmagick++-6.q16-dev libcppunit-dev wget
        wget https://github.com/Wargus/stratagus/archive/master.zip
        unzip master.zip

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR=${{github.workspace}}/stratagus-master/gameheaders

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  windows_build:
    name: Windows build
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    
    - name: Install dependencies
      run:  |
        if ($null -eq $env:GIT_TAG_NAME) { $env:RELEASE = 'master-builds' } else { $env:RELEASE = $env:GIT_TAG_NAME }
        if ($null -eq $env:GIT_TAG_NAME) { $env:SRCTAG = 'master' } else { $env:SRCTAG = $env:GIT_TAG_NAME }
        Invoke-WebRequest https://github.com/Wargus/win32-stratagus-dependencies/releases/download/$env:RELEASE/dependencies.zip -OutFile ${{github.workspace}}/dependencies.zip
        Expand-Archive ${{github.workspace}}/dependencies.zip -DestinationPath ${{github.workspace}}/
        mkdir build
        Invoke-WebRequest https://github.com/Wargus/stratagus/releases/download/$env:RELEASE/compiled-binaries.zip -OutFile ${{github.workspace}}/compiled-binaries.zip
        Expand-Archive compiled-binaries.zip -DestinationPath ${{github.workspace}}/build/
        Invoke-WebRequest https://github.com/Wargus/stratagus/archive/$env:SRCTAG.zip -OutFile ${{github.workspace}}/stratagus-source.zip
        Expand-Archive stratagus-source.zip -DestinationPath ${{github.workspace}}/
        if ($null -ne $env:GIT_TAG_NAME) { move stratagus-$env:SRCTAG stratagus-master }

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -T v141_xp -A win32 -DCMAKE_PREFIX_PATH="${{github.workspace}}\\dependencies" -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR="${{github.workspace}}\\stratagus-master\\gameheaders" -DENABLE_NSIS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v3
      with:
        name: Stargus
        path: build/Stargus-*.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: 'Automatic builds from the master branch'
        draft: false
        prerelease: true
        files: build/Stargus-*.exe

# deploy:
#   - provider: GitHub
#     release: master-builds
#     description: 'Automatic builds from the master branch'
#     auth_token:
#       secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
#     artifact: /.*exe/
#     draft: false
#     prerelease: true
#     on:
#       branch: master
#   - provider: GitHub
#     release: $(APPVEYOR_REPO_TAG_NAME)
#     description: 'Release'
#     auth_token:
#       secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
#     artifact: /.*exe/
#     draft: false
#     prerelease: false
#     on:
#       appveyor_repo_tag: true
